// Code generated by ent, DO NOT EDIT.

package eventreconciliation

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/bengobox/game-stats-api/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.EventReconciliation {
	return predicate.EventReconciliation(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.EventReconciliation {
	return predicate.EventReconciliation(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.EventReconciliation {
	return predicate.EventReconciliation(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.EventReconciliation {
	return predicate.EventReconciliation(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.EventReconciliation {
	return predicate.EventReconciliation(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.EventReconciliation {
	return predicate.EventReconciliation(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.EventReconciliation {
	return predicate.EventReconciliation(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.EventReconciliation {
	return predicate.EventReconciliation(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.EventReconciliation {
	return predicate.EventReconciliation(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.EventReconciliation {
	return predicate.EventReconciliation(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.EventReconciliation {
	return predicate.EventReconciliation(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.EventReconciliation {
	return predicate.EventReconciliation(sql.FieldEQ(FieldDeletedAt, v))
}

// ReconciledAt applies equality check predicate on the "reconciled_at" field. It's identical to ReconciledAtEQ.
func ReconciledAt(v time.Time) predicate.EventReconciliation {
	return predicate.EventReconciliation(sql.FieldEQ(FieldReconciledAt, v))
}

// ReconciledBy applies equality check predicate on the "reconciled_by" field. It's identical to ReconciledByEQ.
func ReconciledBy(v string) predicate.EventReconciliation {
	return predicate.EventReconciliation(sql.FieldEQ(FieldReconciledBy, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.EventReconciliation {
	return predicate.EventReconciliation(sql.FieldEQ(FieldStatus, v))
}

// Comments applies equality check predicate on the "comments" field. It's identical to CommentsEQ.
func Comments(v string) predicate.EventReconciliation {
	return predicate.EventReconciliation(sql.FieldEQ(FieldComments, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.EventReconciliation {
	return predicate.EventReconciliation(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.EventReconciliation {
	return predicate.EventReconciliation(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.EventReconciliation {
	return predicate.EventReconciliation(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.EventReconciliation {
	return predicate.EventReconciliation(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.EventReconciliation {
	return predicate.EventReconciliation(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.EventReconciliation {
	return predicate.EventReconciliation(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.EventReconciliation {
	return predicate.EventReconciliation(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.EventReconciliation {
	return predicate.EventReconciliation(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.EventReconciliation {
	return predicate.EventReconciliation(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.EventReconciliation {
	return predicate.EventReconciliation(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.EventReconciliation {
	return predicate.EventReconciliation(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.EventReconciliation {
	return predicate.EventReconciliation(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.EventReconciliation {
	return predicate.EventReconciliation(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.EventReconciliation {
	return predicate.EventReconciliation(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.EventReconciliation {
	return predicate.EventReconciliation(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.EventReconciliation {
	return predicate.EventReconciliation(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.EventReconciliation {
	return predicate.EventReconciliation(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.EventReconciliation {
	return predicate.EventReconciliation(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.EventReconciliation {
	return predicate.EventReconciliation(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.EventReconciliation {
	return predicate.EventReconciliation(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.EventReconciliation {
	return predicate.EventReconciliation(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.EventReconciliation {
	return predicate.EventReconciliation(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.EventReconciliation {
	return predicate.EventReconciliation(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.EventReconciliation {
	return predicate.EventReconciliation(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.EventReconciliation {
	return predicate.EventReconciliation(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.EventReconciliation {
	return predicate.EventReconciliation(sql.FieldNotNull(FieldDeletedAt))
}

// ReconciledAtEQ applies the EQ predicate on the "reconciled_at" field.
func ReconciledAtEQ(v time.Time) predicate.EventReconciliation {
	return predicate.EventReconciliation(sql.FieldEQ(FieldReconciledAt, v))
}

// ReconciledAtNEQ applies the NEQ predicate on the "reconciled_at" field.
func ReconciledAtNEQ(v time.Time) predicate.EventReconciliation {
	return predicate.EventReconciliation(sql.FieldNEQ(FieldReconciledAt, v))
}

// ReconciledAtIn applies the In predicate on the "reconciled_at" field.
func ReconciledAtIn(vs ...time.Time) predicate.EventReconciliation {
	return predicate.EventReconciliation(sql.FieldIn(FieldReconciledAt, vs...))
}

// ReconciledAtNotIn applies the NotIn predicate on the "reconciled_at" field.
func ReconciledAtNotIn(vs ...time.Time) predicate.EventReconciliation {
	return predicate.EventReconciliation(sql.FieldNotIn(FieldReconciledAt, vs...))
}

// ReconciledAtGT applies the GT predicate on the "reconciled_at" field.
func ReconciledAtGT(v time.Time) predicate.EventReconciliation {
	return predicate.EventReconciliation(sql.FieldGT(FieldReconciledAt, v))
}

// ReconciledAtGTE applies the GTE predicate on the "reconciled_at" field.
func ReconciledAtGTE(v time.Time) predicate.EventReconciliation {
	return predicate.EventReconciliation(sql.FieldGTE(FieldReconciledAt, v))
}

// ReconciledAtLT applies the LT predicate on the "reconciled_at" field.
func ReconciledAtLT(v time.Time) predicate.EventReconciliation {
	return predicate.EventReconciliation(sql.FieldLT(FieldReconciledAt, v))
}

// ReconciledAtLTE applies the LTE predicate on the "reconciled_at" field.
func ReconciledAtLTE(v time.Time) predicate.EventReconciliation {
	return predicate.EventReconciliation(sql.FieldLTE(FieldReconciledAt, v))
}

// ReconciledByEQ applies the EQ predicate on the "reconciled_by" field.
func ReconciledByEQ(v string) predicate.EventReconciliation {
	return predicate.EventReconciliation(sql.FieldEQ(FieldReconciledBy, v))
}

// ReconciledByNEQ applies the NEQ predicate on the "reconciled_by" field.
func ReconciledByNEQ(v string) predicate.EventReconciliation {
	return predicate.EventReconciliation(sql.FieldNEQ(FieldReconciledBy, v))
}

// ReconciledByIn applies the In predicate on the "reconciled_by" field.
func ReconciledByIn(vs ...string) predicate.EventReconciliation {
	return predicate.EventReconciliation(sql.FieldIn(FieldReconciledBy, vs...))
}

// ReconciledByNotIn applies the NotIn predicate on the "reconciled_by" field.
func ReconciledByNotIn(vs ...string) predicate.EventReconciliation {
	return predicate.EventReconciliation(sql.FieldNotIn(FieldReconciledBy, vs...))
}

// ReconciledByGT applies the GT predicate on the "reconciled_by" field.
func ReconciledByGT(v string) predicate.EventReconciliation {
	return predicate.EventReconciliation(sql.FieldGT(FieldReconciledBy, v))
}

// ReconciledByGTE applies the GTE predicate on the "reconciled_by" field.
func ReconciledByGTE(v string) predicate.EventReconciliation {
	return predicate.EventReconciliation(sql.FieldGTE(FieldReconciledBy, v))
}

// ReconciledByLT applies the LT predicate on the "reconciled_by" field.
func ReconciledByLT(v string) predicate.EventReconciliation {
	return predicate.EventReconciliation(sql.FieldLT(FieldReconciledBy, v))
}

// ReconciledByLTE applies the LTE predicate on the "reconciled_by" field.
func ReconciledByLTE(v string) predicate.EventReconciliation {
	return predicate.EventReconciliation(sql.FieldLTE(FieldReconciledBy, v))
}

// ReconciledByContains applies the Contains predicate on the "reconciled_by" field.
func ReconciledByContains(v string) predicate.EventReconciliation {
	return predicate.EventReconciliation(sql.FieldContains(FieldReconciledBy, v))
}

// ReconciledByHasPrefix applies the HasPrefix predicate on the "reconciled_by" field.
func ReconciledByHasPrefix(v string) predicate.EventReconciliation {
	return predicate.EventReconciliation(sql.FieldHasPrefix(FieldReconciledBy, v))
}

// ReconciledByHasSuffix applies the HasSuffix predicate on the "reconciled_by" field.
func ReconciledByHasSuffix(v string) predicate.EventReconciliation {
	return predicate.EventReconciliation(sql.FieldHasSuffix(FieldReconciledBy, v))
}

// ReconciledByEqualFold applies the EqualFold predicate on the "reconciled_by" field.
func ReconciledByEqualFold(v string) predicate.EventReconciliation {
	return predicate.EventReconciliation(sql.FieldEqualFold(FieldReconciledBy, v))
}

// ReconciledByContainsFold applies the ContainsFold predicate on the "reconciled_by" field.
func ReconciledByContainsFold(v string) predicate.EventReconciliation {
	return predicate.EventReconciliation(sql.FieldContainsFold(FieldReconciledBy, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.EventReconciliation {
	return predicate.EventReconciliation(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.EventReconciliation {
	return predicate.EventReconciliation(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.EventReconciliation {
	return predicate.EventReconciliation(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.EventReconciliation {
	return predicate.EventReconciliation(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.EventReconciliation {
	return predicate.EventReconciliation(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.EventReconciliation {
	return predicate.EventReconciliation(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.EventReconciliation {
	return predicate.EventReconciliation(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.EventReconciliation {
	return predicate.EventReconciliation(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.EventReconciliation {
	return predicate.EventReconciliation(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.EventReconciliation {
	return predicate.EventReconciliation(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.EventReconciliation {
	return predicate.EventReconciliation(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.EventReconciliation {
	return predicate.EventReconciliation(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.EventReconciliation {
	return predicate.EventReconciliation(sql.FieldContainsFold(FieldStatus, v))
}

// CommentsEQ applies the EQ predicate on the "comments" field.
func CommentsEQ(v string) predicate.EventReconciliation {
	return predicate.EventReconciliation(sql.FieldEQ(FieldComments, v))
}

// CommentsNEQ applies the NEQ predicate on the "comments" field.
func CommentsNEQ(v string) predicate.EventReconciliation {
	return predicate.EventReconciliation(sql.FieldNEQ(FieldComments, v))
}

// CommentsIn applies the In predicate on the "comments" field.
func CommentsIn(vs ...string) predicate.EventReconciliation {
	return predicate.EventReconciliation(sql.FieldIn(FieldComments, vs...))
}

// CommentsNotIn applies the NotIn predicate on the "comments" field.
func CommentsNotIn(vs ...string) predicate.EventReconciliation {
	return predicate.EventReconciliation(sql.FieldNotIn(FieldComments, vs...))
}

// CommentsGT applies the GT predicate on the "comments" field.
func CommentsGT(v string) predicate.EventReconciliation {
	return predicate.EventReconciliation(sql.FieldGT(FieldComments, v))
}

// CommentsGTE applies the GTE predicate on the "comments" field.
func CommentsGTE(v string) predicate.EventReconciliation {
	return predicate.EventReconciliation(sql.FieldGTE(FieldComments, v))
}

// CommentsLT applies the LT predicate on the "comments" field.
func CommentsLT(v string) predicate.EventReconciliation {
	return predicate.EventReconciliation(sql.FieldLT(FieldComments, v))
}

// CommentsLTE applies the LTE predicate on the "comments" field.
func CommentsLTE(v string) predicate.EventReconciliation {
	return predicate.EventReconciliation(sql.FieldLTE(FieldComments, v))
}

// CommentsContains applies the Contains predicate on the "comments" field.
func CommentsContains(v string) predicate.EventReconciliation {
	return predicate.EventReconciliation(sql.FieldContains(FieldComments, v))
}

// CommentsHasPrefix applies the HasPrefix predicate on the "comments" field.
func CommentsHasPrefix(v string) predicate.EventReconciliation {
	return predicate.EventReconciliation(sql.FieldHasPrefix(FieldComments, v))
}

// CommentsHasSuffix applies the HasSuffix predicate on the "comments" field.
func CommentsHasSuffix(v string) predicate.EventReconciliation {
	return predicate.EventReconciliation(sql.FieldHasSuffix(FieldComments, v))
}

// CommentsIsNil applies the IsNil predicate on the "comments" field.
func CommentsIsNil() predicate.EventReconciliation {
	return predicate.EventReconciliation(sql.FieldIsNull(FieldComments))
}

// CommentsNotNil applies the NotNil predicate on the "comments" field.
func CommentsNotNil() predicate.EventReconciliation {
	return predicate.EventReconciliation(sql.FieldNotNull(FieldComments))
}

// CommentsEqualFold applies the EqualFold predicate on the "comments" field.
func CommentsEqualFold(v string) predicate.EventReconciliation {
	return predicate.EventReconciliation(sql.FieldEqualFold(FieldComments, v))
}

// CommentsContainsFold applies the ContainsFold predicate on the "comments" field.
func CommentsContainsFold(v string) predicate.EventReconciliation {
	return predicate.EventReconciliation(sql.FieldContainsFold(FieldComments, v))
}

// HasEvent applies the HasEdge predicate on the "event" edge.
func HasEvent() predicate.EventReconciliation {
	return predicate.EventReconciliation(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, EventTable, EventColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasEventWith applies the HasEdge predicate on the "event" edge with a given conditions (other predicates).
func HasEventWith(preds ...predicate.Event) predicate.EventReconciliation {
	return predicate.EventReconciliation(func(s *sql.Selector) {
		step := newEventStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.EventReconciliation) predicate.EventReconciliation {
	return predicate.EventReconciliation(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.EventReconciliation) predicate.EventReconciliation {
	return predicate.EventReconciliation(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.EventReconciliation) predicate.EventReconciliation {
	return predicate.EventReconciliation(sql.NotPredicates(p))
}
