// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/bengobox/game-stats-api/ent/continent"
	"github.com/bengobox/game-stats-api/ent/world"
	"github.com/google/uuid"
)

// Continent is the model entity for the Continent schema.
type Continent struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Slug holds the value of the "slug" field.
	Slug string `json:"slug,omitempty"`
	// Description holds the value of the "description" field.
	Description *string `json:"description,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ContinentQuery when eager-loading is set.
	Edges            ContinentEdges `json:"edges"`
	world_continents *uuid.UUID
	selectValues     sql.SelectValues
}

// ContinentEdges holds the relations/edges for other nodes in the graph.
type ContinentEdges struct {
	// World holds the value of the world edge.
	World *World `json:"world,omitempty"`
	// Countries holds the value of the countries edge.
	Countries []*Country `json:"countries,omitempty"`
	// ManagedBy holds the value of the managed_by edge.
	ManagedBy []*User `json:"managed_by,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// WorldOrErr returns the World value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ContinentEdges) WorldOrErr() (*World, error) {
	if e.World != nil {
		return e.World, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: world.Label}
	}
	return nil, &NotLoadedError{edge: "world"}
}

// CountriesOrErr returns the Countries value or an error if the edge
// was not loaded in eager-loading.
func (e ContinentEdges) CountriesOrErr() ([]*Country, error) {
	if e.loadedTypes[1] {
		return e.Countries, nil
	}
	return nil, &NotLoadedError{edge: "countries"}
}

// ManagedByOrErr returns the ManagedBy value or an error if the edge
// was not loaded in eager-loading.
func (e ContinentEdges) ManagedByOrErr() ([]*User, error) {
	if e.loadedTypes[2] {
		return e.ManagedBy, nil
	}
	return nil, &NotLoadedError{edge: "managed_by"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Continent) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case continent.FieldName, continent.FieldSlug, continent.FieldDescription:
			values[i] = new(sql.NullString)
		case continent.FieldCreatedAt, continent.FieldUpdatedAt, continent.FieldDeletedAt:
			values[i] = new(sql.NullTime)
		case continent.FieldID:
			values[i] = new(uuid.UUID)
		case continent.ForeignKeys[0]: // world_continents
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Continent fields.
func (_m *Continent) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case continent.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case continent.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case continent.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case continent.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		case continent.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case continent.FieldSlug:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field slug", values[i])
			} else if value.Valid {
				_m.Slug = value.String
			}
		case continent.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = new(string)
				*_m.Description = value.String
			}
		case continent.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field world_continents", values[i])
			} else if value.Valid {
				_m.world_continents = new(uuid.UUID)
				*_m.world_continents = *value.S.(*uuid.UUID)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Continent.
// This includes values selected through modifiers, order, etc.
func (_m *Continent) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryWorld queries the "world" edge of the Continent entity.
func (_m *Continent) QueryWorld() *WorldQuery {
	return NewContinentClient(_m.config).QueryWorld(_m)
}

// QueryCountries queries the "countries" edge of the Continent entity.
func (_m *Continent) QueryCountries() *CountryQuery {
	return NewContinentClient(_m.config).QueryCountries(_m)
}

// QueryManagedBy queries the "managed_by" edge of the Continent entity.
func (_m *Continent) QueryManagedBy() *UserQuery {
	return NewContinentClient(_m.config).QueryManagedBy(_m)
}

// Update returns a builder for updating this Continent.
// Note that you need to call Continent.Unwrap() before calling this method if this Continent
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Continent) Update() *ContinentUpdateOne {
	return NewContinentClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Continent entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Continent) Unwrap() *Continent {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Continent is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Continent) String() string {
	var builder strings.Builder
	builder.WriteString("Continent(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("slug=")
	builder.WriteString(_m.Slug)
	builder.WriteString(", ")
	if v := _m.Description; v != nil {
		builder.WriteString("description=")
		builder.WriteString(*v)
	}
	builder.WriteByte(')')
	return builder.String()
}

// Continents is a parsable slice of Continent.
type Continents []*Continent
