// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/bengobox/game-stats-api/ent/game"
	"github.com/bengobox/game-stats-api/ent/gameevent"
	"github.com/bengobox/game-stats-api/ent/player"
	"github.com/google/uuid"
)

// GameEvent is the model entity for the GameEvent schema.
type GameEvent struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// EventType holds the value of the "event_type" field.
	EventType string `json:"event_type,omitempty"`
	// Minute holds the value of the "minute" field.
	Minute int `json:"minute,omitempty"`
	// Second holds the value of the "second" field.
	Second int `json:"second,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// Metadata holds the value of the "metadata" field.
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the GameEventQuery when eager-loading is set.
	Edges              GameEventEdges `json:"edges"`
	game_game_events   *uuid.UUID
	player_game_events *uuid.UUID
	selectValues       sql.SelectValues
}

// GameEventEdges holds the relations/edges for other nodes in the graph.
type GameEventEdges struct {
	// Game holds the value of the game edge.
	Game *Game `json:"game,omitempty"`
	// Player holds the value of the player edge.
	Player *Player `json:"player,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// GameOrErr returns the Game value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e GameEventEdges) GameOrErr() (*Game, error) {
	if e.Game != nil {
		return e.Game, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: game.Label}
	}
	return nil, &NotLoadedError{edge: "game"}
}

// PlayerOrErr returns the Player value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e GameEventEdges) PlayerOrErr() (*Player, error) {
	if e.Player != nil {
		return e.Player, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: player.Label}
	}
	return nil, &NotLoadedError{edge: "player"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*GameEvent) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case gameevent.FieldMetadata:
			values[i] = new([]byte)
		case gameevent.FieldMinute, gameevent.FieldSecond:
			values[i] = new(sql.NullInt64)
		case gameevent.FieldEventType, gameevent.FieldDescription:
			values[i] = new(sql.NullString)
		case gameevent.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case gameevent.FieldID:
			values[i] = new(uuid.UUID)
		case gameevent.ForeignKeys[0]: // game_game_events
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case gameevent.ForeignKeys[1]: // player_game_events
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the GameEvent fields.
func (_m *GameEvent) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case gameevent.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case gameevent.FieldEventType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field event_type", values[i])
			} else if value.Valid {
				_m.EventType = value.String
			}
		case gameevent.FieldMinute:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field minute", values[i])
			} else if value.Valid {
				_m.Minute = int(value.Int64)
			}
		case gameevent.FieldSecond:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field second", values[i])
			} else if value.Valid {
				_m.Second = int(value.Int64)
			}
		case gameevent.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case gameevent.FieldMetadata:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field metadata", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Metadata); err != nil {
					return fmt.Errorf("unmarshal field metadata: %w", err)
				}
			}
		case gameevent.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case gameevent.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field game_game_events", values[i])
			} else if value.Valid {
				_m.game_game_events = new(uuid.UUID)
				*_m.game_game_events = *value.S.(*uuid.UUID)
			}
		case gameevent.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field player_game_events", values[i])
			} else if value.Valid {
				_m.player_game_events = new(uuid.UUID)
				*_m.player_game_events = *value.S.(*uuid.UUID)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the GameEvent.
// This includes values selected through modifiers, order, etc.
func (_m *GameEvent) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryGame queries the "game" edge of the GameEvent entity.
func (_m *GameEvent) QueryGame() *GameQuery {
	return NewGameEventClient(_m.config).QueryGame(_m)
}

// QueryPlayer queries the "player" edge of the GameEvent entity.
func (_m *GameEvent) QueryPlayer() *PlayerQuery {
	return NewGameEventClient(_m.config).QueryPlayer(_m)
}

// Update returns a builder for updating this GameEvent.
// Note that you need to call GameEvent.Unwrap() before calling this method if this GameEvent
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *GameEvent) Update() *GameEventUpdateOne {
	return NewGameEventClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the GameEvent entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *GameEvent) Unwrap() *GameEvent {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: GameEvent is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *GameEvent) String() string {
	var builder strings.Builder
	builder.WriteString("GameEvent(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("event_type=")
	builder.WriteString(_m.EventType)
	builder.WriteString(", ")
	builder.WriteString("minute=")
	builder.WriteString(fmt.Sprintf("%v", _m.Minute))
	builder.WriteString(", ")
	builder.WriteString("second=")
	builder.WriteString(fmt.Sprintf("%v", _m.Second))
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("metadata=")
	builder.WriteString(fmt.Sprintf("%v", _m.Metadata))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// GameEvents is a parsable slice of GameEvent.
type GameEvents []*GameEvent
