// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/bengobox/game-stats-api/ent/mvp_nomination"
	"github.com/bengobox/game-stats-api/ent/player"
	"github.com/bengobox/game-stats-api/ent/spiritscore"
	"github.com/google/uuid"
)

// MVP_Nomination is the model entity for the MVP_Nomination schema.
type MVP_Nomination struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Category holds the value of the "category" field.
	Category string `json:"category,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the MVP_NominationQuery when eager-loading is set.
	Edges                        MVP_NominationEdges `json:"edges"`
	player_mvp_nominations       *uuid.UUID
	spirit_score_mvp_nominations *uuid.UUID
	selectValues                 sql.SelectValues
}

// MVP_NominationEdges holds the relations/edges for other nodes in the graph.
type MVP_NominationEdges struct {
	// SpiritScore holds the value of the spirit_score edge.
	SpiritScore *SpiritScore `json:"spirit_score,omitempty"`
	// Player holds the value of the player edge.
	Player *Player `json:"player,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// SpiritScoreOrErr returns the SpiritScore value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e MVP_NominationEdges) SpiritScoreOrErr() (*SpiritScore, error) {
	if e.SpiritScore != nil {
		return e.SpiritScore, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: spiritscore.Label}
	}
	return nil, &NotLoadedError{edge: "spirit_score"}
}

// PlayerOrErr returns the Player value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e MVP_NominationEdges) PlayerOrErr() (*Player, error) {
	if e.Player != nil {
		return e.Player, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: player.Label}
	}
	return nil, &NotLoadedError{edge: "player"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*MVP_Nomination) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case mvp_nomination.FieldCategory:
			values[i] = new(sql.NullString)
		case mvp_nomination.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case mvp_nomination.FieldID:
			values[i] = new(uuid.UUID)
		case mvp_nomination.ForeignKeys[0]: // player_mvp_nominations
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case mvp_nomination.ForeignKeys[1]: // spirit_score_mvp_nominations
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the MVP_Nomination fields.
func (_m *MVP_Nomination) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case mvp_nomination.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case mvp_nomination.FieldCategory:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field category", values[i])
			} else if value.Valid {
				_m.Category = value.String
			}
		case mvp_nomination.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case mvp_nomination.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field player_mvp_nominations", values[i])
			} else if value.Valid {
				_m.player_mvp_nominations = new(uuid.UUID)
				*_m.player_mvp_nominations = *value.S.(*uuid.UUID)
			}
		case mvp_nomination.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field spirit_score_mvp_nominations", values[i])
			} else if value.Valid {
				_m.spirit_score_mvp_nominations = new(uuid.UUID)
				*_m.spirit_score_mvp_nominations = *value.S.(*uuid.UUID)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the MVP_Nomination.
// This includes values selected through modifiers, order, etc.
func (_m *MVP_Nomination) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QuerySpiritScore queries the "spirit_score" edge of the MVP_Nomination entity.
func (_m *MVP_Nomination) QuerySpiritScore() *SpiritScoreQuery {
	return NewMVPNominationClient(_m.config).QuerySpiritScore(_m)
}

// QueryPlayer queries the "player" edge of the MVP_Nomination entity.
func (_m *MVP_Nomination) QueryPlayer() *PlayerQuery {
	return NewMVPNominationClient(_m.config).QueryPlayer(_m)
}

// Update returns a builder for updating this MVP_Nomination.
// Note that you need to call MVP_Nomination.Unwrap() before calling this method if this MVP_Nomination
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *MVP_Nomination) Update() *MVPNominationUpdateOne {
	return NewMVPNominationClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the MVP_Nomination entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *MVP_Nomination) Unwrap() *MVP_Nomination {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: MVP_Nomination is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *MVP_Nomination) String() string {
	var builder strings.Builder
	builder.WriteString("MVP_Nomination(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("category=")
	builder.WriteString(_m.Category)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// MVP_Nominations is a parsable slice of MVP_Nomination.
type MVP_Nominations []*MVP_Nomination
