// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/game-stats-api/ent/gameevent"
	"github.com/bengobox/game-stats-api/ent/mvp_nomination"
	"github.com/bengobox/game-stats-api/ent/player"
	"github.com/bengobox/game-stats-api/ent/predicate"
	"github.com/bengobox/game-stats-api/ent/scoring"
	"github.com/bengobox/game-stats-api/ent/spiritnomination"
	"github.com/bengobox/game-stats-api/ent/team"
	"github.com/google/uuid"
)

// PlayerQuery is the builder for querying Player entities.
type PlayerQuery struct {
	config
	ctx                   *QueryContext
	order                 []player.OrderOption
	inters                []Interceptor
	predicates            []predicate.Player
	withTeam              *TeamQuery
	withScores            *ScoringQuery
	withGameEvents        *GameEventQuery
	withMvpNominations    *MVPNominationQuery
	withSpiritNominations *SpiritNominationQuery
	withFKs               bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the PlayerQuery builder.
func (_q *PlayerQuery) Where(ps ...predicate.Player) *PlayerQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *PlayerQuery) Limit(limit int) *PlayerQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *PlayerQuery) Offset(offset int) *PlayerQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *PlayerQuery) Unique(unique bool) *PlayerQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *PlayerQuery) Order(o ...player.OrderOption) *PlayerQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryTeam chains the current query on the "team" edge.
func (_q *PlayerQuery) QueryTeam() *TeamQuery {
	query := (&TeamClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(player.Table, player.FieldID, selector),
			sqlgraph.To(team.Table, team.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, player.TeamTable, player.TeamColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryScores chains the current query on the "scores" edge.
func (_q *PlayerQuery) QueryScores() *ScoringQuery {
	query := (&ScoringClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(player.Table, player.FieldID, selector),
			sqlgraph.To(scoring.Table, scoring.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, player.ScoresTable, player.ScoresColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryGameEvents chains the current query on the "game_events" edge.
func (_q *PlayerQuery) QueryGameEvents() *GameEventQuery {
	query := (&GameEventClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(player.Table, player.FieldID, selector),
			sqlgraph.To(gameevent.Table, gameevent.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, player.GameEventsTable, player.GameEventsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryMvpNominations chains the current query on the "mvp_nominations" edge.
func (_q *PlayerQuery) QueryMvpNominations() *MVPNominationQuery {
	query := (&MVPNominationClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(player.Table, player.FieldID, selector),
			sqlgraph.To(mvp_nomination.Table, mvp_nomination.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, player.MvpNominationsTable, player.MvpNominationsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QuerySpiritNominations chains the current query on the "spirit_nominations" edge.
func (_q *PlayerQuery) QuerySpiritNominations() *SpiritNominationQuery {
	query := (&SpiritNominationClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(player.Table, player.FieldID, selector),
			sqlgraph.To(spiritnomination.Table, spiritnomination.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, player.SpiritNominationsTable, player.SpiritNominationsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Player entity from the query.
// Returns a *NotFoundError when no Player was found.
func (_q *PlayerQuery) First(ctx context.Context) (*Player, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{player.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *PlayerQuery) FirstX(ctx context.Context) *Player {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Player ID from the query.
// Returns a *NotFoundError when no Player ID was found.
func (_q *PlayerQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{player.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *PlayerQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Player entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Player entity is found.
// Returns a *NotFoundError when no Player entities are found.
func (_q *PlayerQuery) Only(ctx context.Context) (*Player, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{player.Label}
	default:
		return nil, &NotSingularError{player.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *PlayerQuery) OnlyX(ctx context.Context) *Player {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Player ID in the query.
// Returns a *NotSingularError when more than one Player ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *PlayerQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{player.Label}
	default:
		err = &NotSingularError{player.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *PlayerQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Players.
func (_q *PlayerQuery) All(ctx context.Context) ([]*Player, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Player, *PlayerQuery]()
	return withInterceptors[[]*Player](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *PlayerQuery) AllX(ctx context.Context) []*Player {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Player IDs.
func (_q *PlayerQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(player.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *PlayerQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *PlayerQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*PlayerQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *PlayerQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *PlayerQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *PlayerQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the PlayerQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *PlayerQuery) Clone() *PlayerQuery {
	if _q == nil {
		return nil
	}
	return &PlayerQuery{
		config:                _q.config,
		ctx:                   _q.ctx.Clone(),
		order:                 append([]player.OrderOption{}, _q.order...),
		inters:                append([]Interceptor{}, _q.inters...),
		predicates:            append([]predicate.Player{}, _q.predicates...),
		withTeam:              _q.withTeam.Clone(),
		withScores:            _q.withScores.Clone(),
		withGameEvents:        _q.withGameEvents.Clone(),
		withMvpNominations:    _q.withMvpNominations.Clone(),
		withSpiritNominations: _q.withSpiritNominations.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithTeam tells the query-builder to eager-load the nodes that are connected to
// the "team" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *PlayerQuery) WithTeam(opts ...func(*TeamQuery)) *PlayerQuery {
	query := (&TeamClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withTeam = query
	return _q
}

// WithScores tells the query-builder to eager-load the nodes that are connected to
// the "scores" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *PlayerQuery) WithScores(opts ...func(*ScoringQuery)) *PlayerQuery {
	query := (&ScoringClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withScores = query
	return _q
}

// WithGameEvents tells the query-builder to eager-load the nodes that are connected to
// the "game_events" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *PlayerQuery) WithGameEvents(opts ...func(*GameEventQuery)) *PlayerQuery {
	query := (&GameEventClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withGameEvents = query
	return _q
}

// WithMvpNominations tells the query-builder to eager-load the nodes that are connected to
// the "mvp_nominations" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *PlayerQuery) WithMvpNominations(opts ...func(*MVPNominationQuery)) *PlayerQuery {
	query := (&MVPNominationClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withMvpNominations = query
	return _q
}

// WithSpiritNominations tells the query-builder to eager-load the nodes that are connected to
// the "spirit_nominations" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *PlayerQuery) WithSpiritNominations(opts ...func(*SpiritNominationQuery)) *PlayerQuery {
	query := (&SpiritNominationClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withSpiritNominations = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Player.Query().
//		GroupBy(player.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *PlayerQuery) GroupBy(field string, fields ...string) *PlayerGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &PlayerGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = player.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.Player.Query().
//		Select(player.FieldCreatedAt).
//		Scan(ctx, &v)
func (_q *PlayerQuery) Select(fields ...string) *PlayerSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &PlayerSelect{PlayerQuery: _q}
	sbuild.label = player.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a PlayerSelect configured with the given aggregations.
func (_q *PlayerQuery) Aggregate(fns ...AggregateFunc) *PlayerSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *PlayerQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !player.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *PlayerQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Player, error) {
	var (
		nodes       = []*Player{}
		withFKs     = _q.withFKs
		_spec       = _q.querySpec()
		loadedTypes = [5]bool{
			_q.withTeam != nil,
			_q.withScores != nil,
			_q.withGameEvents != nil,
			_q.withMvpNominations != nil,
			_q.withSpiritNominations != nil,
		}
	)
	if _q.withTeam != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, player.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Player).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Player{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withTeam; query != nil {
		if err := _q.loadTeam(ctx, query, nodes, nil,
			func(n *Player, e *Team) { n.Edges.Team = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withScores; query != nil {
		if err := _q.loadScores(ctx, query, nodes,
			func(n *Player) { n.Edges.Scores = []*Scoring{} },
			func(n *Player, e *Scoring) { n.Edges.Scores = append(n.Edges.Scores, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withGameEvents; query != nil {
		if err := _q.loadGameEvents(ctx, query, nodes,
			func(n *Player) { n.Edges.GameEvents = []*GameEvent{} },
			func(n *Player, e *GameEvent) { n.Edges.GameEvents = append(n.Edges.GameEvents, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withMvpNominations; query != nil {
		if err := _q.loadMvpNominations(ctx, query, nodes,
			func(n *Player) { n.Edges.MvpNominations = []*MVP_Nomination{} },
			func(n *Player, e *MVP_Nomination) { n.Edges.MvpNominations = append(n.Edges.MvpNominations, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withSpiritNominations; query != nil {
		if err := _q.loadSpiritNominations(ctx, query, nodes,
			func(n *Player) { n.Edges.SpiritNominations = []*SpiritNomination{} },
			func(n *Player, e *SpiritNomination) { n.Edges.SpiritNominations = append(n.Edges.SpiritNominations, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *PlayerQuery) loadTeam(ctx context.Context, query *TeamQuery, nodes []*Player, init func(*Player), assign func(*Player, *Team)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*Player)
	for i := range nodes {
		if nodes[i].team_players == nil {
			continue
		}
		fk := *nodes[i].team_players
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(team.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "team_players" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *PlayerQuery) loadScores(ctx context.Context, query *ScoringQuery, nodes []*Player, init func(*Player), assign func(*Player, *Scoring)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Player)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.Scoring(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(player.ScoresColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.player_scores
		if fk == nil {
			return fmt.Errorf(`foreign-key "player_scores" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "player_scores" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *PlayerQuery) loadGameEvents(ctx context.Context, query *GameEventQuery, nodes []*Player, init func(*Player), assign func(*Player, *GameEvent)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Player)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.GameEvent(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(player.GameEventsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.player_game_events
		if fk == nil {
			return fmt.Errorf(`foreign-key "player_game_events" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "player_game_events" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *PlayerQuery) loadMvpNominations(ctx context.Context, query *MVPNominationQuery, nodes []*Player, init func(*Player), assign func(*Player, *MVP_Nomination)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Player)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.MVP_Nomination(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(player.MvpNominationsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.player_mvp_nominations
		if fk == nil {
			return fmt.Errorf(`foreign-key "player_mvp_nominations" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "player_mvp_nominations" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *PlayerQuery) loadSpiritNominations(ctx context.Context, query *SpiritNominationQuery, nodes []*Player, init func(*Player), assign func(*Player, *SpiritNomination)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Player)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.SpiritNomination(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(player.SpiritNominationsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.player_spirit_nominations
		if fk == nil {
			return fmt.Errorf(`foreign-key "player_spirit_nominations" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "player_spirit_nominations" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *PlayerQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *PlayerQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(player.Table, player.Columns, sqlgraph.NewFieldSpec(player.FieldID, field.TypeUUID))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, player.FieldID)
		for i := range fields {
			if fields[i] != player.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *PlayerQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(player.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = player.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// PlayerGroupBy is the group-by builder for Player entities.
type PlayerGroupBy struct {
	selector
	build *PlayerQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *PlayerGroupBy) Aggregate(fns ...AggregateFunc) *PlayerGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *PlayerGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PlayerQuery, *PlayerGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *PlayerGroupBy) sqlScan(ctx context.Context, root *PlayerQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// PlayerSelect is the builder for selecting fields of Player entities.
type PlayerSelect struct {
	*PlayerQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *PlayerSelect) Aggregate(fns ...AggregateFunc) *PlayerSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *PlayerSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PlayerQuery, *PlayerSelect](ctx, _s.PlayerQuery, _s, _s.inters, v)
}

func (_s *PlayerSelect) sqlScan(ctx context.Context, root *PlayerQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
