// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/game-stats-api/ent/game"
	"github.com/bengobox/game-stats-api/ent/predicate"
	"github.com/bengobox/game-stats-api/ent/scoreeditrequest"
	"github.com/bengobox/game-stats-api/ent/user"
	"github.com/google/uuid"
)

// ScoreEditRequestUpdate is the builder for updating ScoreEditRequest entities.
type ScoreEditRequestUpdate struct {
	config
	hooks    []Hook
	mutation *ScoreEditRequestMutation
}

// Where appends a list predicates to the ScoreEditRequestUpdate builder.
func (_u *ScoreEditRequestUpdate) Where(ps ...predicate.ScoreEditRequest) *ScoreEditRequestUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetGameID sets the "game_id" field.
func (_u *ScoreEditRequestUpdate) SetGameID(v uuid.UUID) *ScoreEditRequestUpdate {
	_u.mutation.SetGameID(v)
	return _u
}

// SetNillableGameID sets the "game_id" field if the given value is not nil.
func (_u *ScoreEditRequestUpdate) SetNillableGameID(v *uuid.UUID) *ScoreEditRequestUpdate {
	if v != nil {
		_u.SetGameID(*v)
	}
	return _u
}

// SetRequestedByID sets the "requested_by_id" field.
func (_u *ScoreEditRequestUpdate) SetRequestedByID(v uuid.UUID) *ScoreEditRequestUpdate {
	_u.mutation.SetRequestedByID(v)
	return _u
}

// SetNillableRequestedByID sets the "requested_by_id" field if the given value is not nil.
func (_u *ScoreEditRequestUpdate) SetNillableRequestedByID(v *uuid.UUID) *ScoreEditRequestUpdate {
	if v != nil {
		_u.SetRequestedByID(*v)
	}
	return _u
}

// SetPreviousHomeScore sets the "previous_home_score" field.
func (_u *ScoreEditRequestUpdate) SetPreviousHomeScore(v int) *ScoreEditRequestUpdate {
	_u.mutation.ResetPreviousHomeScore()
	_u.mutation.SetPreviousHomeScore(v)
	return _u
}

// SetNillablePreviousHomeScore sets the "previous_home_score" field if the given value is not nil.
func (_u *ScoreEditRequestUpdate) SetNillablePreviousHomeScore(v *int) *ScoreEditRequestUpdate {
	if v != nil {
		_u.SetPreviousHomeScore(*v)
	}
	return _u
}

// AddPreviousHomeScore adds value to the "previous_home_score" field.
func (_u *ScoreEditRequestUpdate) AddPreviousHomeScore(v int) *ScoreEditRequestUpdate {
	_u.mutation.AddPreviousHomeScore(v)
	return _u
}

// SetPreviousAwayScore sets the "previous_away_score" field.
func (_u *ScoreEditRequestUpdate) SetPreviousAwayScore(v int) *ScoreEditRequestUpdate {
	_u.mutation.ResetPreviousAwayScore()
	_u.mutation.SetPreviousAwayScore(v)
	return _u
}

// SetNillablePreviousAwayScore sets the "previous_away_score" field if the given value is not nil.
func (_u *ScoreEditRequestUpdate) SetNillablePreviousAwayScore(v *int) *ScoreEditRequestUpdate {
	if v != nil {
		_u.SetPreviousAwayScore(*v)
	}
	return _u
}

// AddPreviousAwayScore adds value to the "previous_away_score" field.
func (_u *ScoreEditRequestUpdate) AddPreviousAwayScore(v int) *ScoreEditRequestUpdate {
	_u.mutation.AddPreviousAwayScore(v)
	return _u
}

// SetNewHomeScore sets the "new_home_score" field.
func (_u *ScoreEditRequestUpdate) SetNewHomeScore(v int) *ScoreEditRequestUpdate {
	_u.mutation.ResetNewHomeScore()
	_u.mutation.SetNewHomeScore(v)
	return _u
}

// SetNillableNewHomeScore sets the "new_home_score" field if the given value is not nil.
func (_u *ScoreEditRequestUpdate) SetNillableNewHomeScore(v *int) *ScoreEditRequestUpdate {
	if v != nil {
		_u.SetNewHomeScore(*v)
	}
	return _u
}

// AddNewHomeScore adds value to the "new_home_score" field.
func (_u *ScoreEditRequestUpdate) AddNewHomeScore(v int) *ScoreEditRequestUpdate {
	_u.mutation.AddNewHomeScore(v)
	return _u
}

// SetNewAwayScore sets the "new_away_score" field.
func (_u *ScoreEditRequestUpdate) SetNewAwayScore(v int) *ScoreEditRequestUpdate {
	_u.mutation.ResetNewAwayScore()
	_u.mutation.SetNewAwayScore(v)
	return _u
}

// SetNillableNewAwayScore sets the "new_away_score" field if the given value is not nil.
func (_u *ScoreEditRequestUpdate) SetNillableNewAwayScore(v *int) *ScoreEditRequestUpdate {
	if v != nil {
		_u.SetNewAwayScore(*v)
	}
	return _u
}

// AddNewAwayScore adds value to the "new_away_score" field.
func (_u *ScoreEditRequestUpdate) AddNewAwayScore(v int) *ScoreEditRequestUpdate {
	_u.mutation.AddNewAwayScore(v)
	return _u
}

// SetReason sets the "reason" field.
func (_u *ScoreEditRequestUpdate) SetReason(v string) *ScoreEditRequestUpdate {
	_u.mutation.SetReason(v)
	return _u
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_u *ScoreEditRequestUpdate) SetNillableReason(v *string) *ScoreEditRequestUpdate {
	if v != nil {
		_u.SetReason(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *ScoreEditRequestUpdate) SetStatus(v string) *ScoreEditRequestUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ScoreEditRequestUpdate) SetNillableStatus(v *string) *ScoreEditRequestUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetRejectionReason sets the "rejection_reason" field.
func (_u *ScoreEditRequestUpdate) SetRejectionReason(v string) *ScoreEditRequestUpdate {
	_u.mutation.SetRejectionReason(v)
	return _u
}

// SetNillableRejectionReason sets the "rejection_reason" field if the given value is not nil.
func (_u *ScoreEditRequestUpdate) SetNillableRejectionReason(v *string) *ScoreEditRequestUpdate {
	if v != nil {
		_u.SetRejectionReason(*v)
	}
	return _u
}

// ClearRejectionReason clears the value of the "rejection_reason" field.
func (_u *ScoreEditRequestUpdate) ClearRejectionReason() *ScoreEditRequestUpdate {
	_u.mutation.ClearRejectionReason()
	return _u
}

// SetReviewedByID sets the "reviewed_by_id" field.
func (_u *ScoreEditRequestUpdate) SetReviewedByID(v uuid.UUID) *ScoreEditRequestUpdate {
	_u.mutation.SetReviewedByID(v)
	return _u
}

// SetNillableReviewedByID sets the "reviewed_by_id" field if the given value is not nil.
func (_u *ScoreEditRequestUpdate) SetNillableReviewedByID(v *uuid.UUID) *ScoreEditRequestUpdate {
	if v != nil {
		_u.SetReviewedByID(*v)
	}
	return _u
}

// ClearReviewedByID clears the value of the "reviewed_by_id" field.
func (_u *ScoreEditRequestUpdate) ClearReviewedByID() *ScoreEditRequestUpdate {
	_u.mutation.ClearReviewedByID()
	return _u
}

// SetReviewedAt sets the "reviewed_at" field.
func (_u *ScoreEditRequestUpdate) SetReviewedAt(v time.Time) *ScoreEditRequestUpdate {
	_u.mutation.SetReviewedAt(v)
	return _u
}

// SetNillableReviewedAt sets the "reviewed_at" field if the given value is not nil.
func (_u *ScoreEditRequestUpdate) SetNillableReviewedAt(v *time.Time) *ScoreEditRequestUpdate {
	if v != nil {
		_u.SetReviewedAt(*v)
	}
	return _u
}

// ClearReviewedAt clears the value of the "reviewed_at" field.
func (_u *ScoreEditRequestUpdate) ClearReviewedAt() *ScoreEditRequestUpdate {
	_u.mutation.ClearReviewedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ScoreEditRequestUpdate) SetUpdatedAt(v time.Time) *ScoreEditRequestUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetPlayerScores sets the "player_scores" field.
func (_u *ScoreEditRequestUpdate) SetPlayerScores(v []map[string]interface{}) *ScoreEditRequestUpdate {
	_u.mutation.SetPlayerScores(v)
	return _u
}

// AppendPlayerScores appends value to the "player_scores" field.
func (_u *ScoreEditRequestUpdate) AppendPlayerScores(v []map[string]interface{}) *ScoreEditRequestUpdate {
	_u.mutation.AppendPlayerScores(v)
	return _u
}

// ClearPlayerScores clears the value of the "player_scores" field.
func (_u *ScoreEditRequestUpdate) ClearPlayerScores() *ScoreEditRequestUpdate {
	_u.mutation.ClearPlayerScores()
	return _u
}

// SetGame sets the "game" edge to the Game entity.
func (_u *ScoreEditRequestUpdate) SetGame(v *Game) *ScoreEditRequestUpdate {
	return _u.SetGameID(v.ID)
}

// SetRequestedBy sets the "requested_by" edge to the User entity.
func (_u *ScoreEditRequestUpdate) SetRequestedBy(v *User) *ScoreEditRequestUpdate {
	return _u.SetRequestedByID(v.ID)
}

// SetReviewedBy sets the "reviewed_by" edge to the User entity.
func (_u *ScoreEditRequestUpdate) SetReviewedBy(v *User) *ScoreEditRequestUpdate {
	return _u.SetReviewedByID(v.ID)
}

// Mutation returns the ScoreEditRequestMutation object of the builder.
func (_u *ScoreEditRequestUpdate) Mutation() *ScoreEditRequestMutation {
	return _u.mutation
}

// ClearGame clears the "game" edge to the Game entity.
func (_u *ScoreEditRequestUpdate) ClearGame() *ScoreEditRequestUpdate {
	_u.mutation.ClearGame()
	return _u
}

// ClearRequestedBy clears the "requested_by" edge to the User entity.
func (_u *ScoreEditRequestUpdate) ClearRequestedBy() *ScoreEditRequestUpdate {
	_u.mutation.ClearRequestedBy()
	return _u
}

// ClearReviewedBy clears the "reviewed_by" edge to the User entity.
func (_u *ScoreEditRequestUpdate) ClearReviewedBy() *ScoreEditRequestUpdate {
	_u.mutation.ClearReviewedBy()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ScoreEditRequestUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ScoreEditRequestUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ScoreEditRequestUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ScoreEditRequestUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ScoreEditRequestUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := scoreeditrequest.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ScoreEditRequestUpdate) check() error {
	if v, ok := _u.mutation.Reason(); ok {
		if err := scoreeditrequest.ReasonValidator(v); err != nil {
			return &ValidationError{Name: "reason", err: fmt.Errorf(`ent: validator failed for field "ScoreEditRequest.reason": %w`, err)}
		}
	}
	if _u.mutation.GameCleared() && len(_u.mutation.GameIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ScoreEditRequest.game"`)
	}
	if _u.mutation.RequestedByCleared() && len(_u.mutation.RequestedByIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ScoreEditRequest.requested_by"`)
	}
	return nil
}

func (_u *ScoreEditRequestUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(scoreeditrequest.Table, scoreeditrequest.Columns, sqlgraph.NewFieldSpec(scoreeditrequest.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.PreviousHomeScore(); ok {
		_spec.SetField(scoreeditrequest.FieldPreviousHomeScore, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPreviousHomeScore(); ok {
		_spec.AddField(scoreeditrequest.FieldPreviousHomeScore, field.TypeInt, value)
	}
	if value, ok := _u.mutation.PreviousAwayScore(); ok {
		_spec.SetField(scoreeditrequest.FieldPreviousAwayScore, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPreviousAwayScore(); ok {
		_spec.AddField(scoreeditrequest.FieldPreviousAwayScore, field.TypeInt, value)
	}
	if value, ok := _u.mutation.NewHomeScore(); ok {
		_spec.SetField(scoreeditrequest.FieldNewHomeScore, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedNewHomeScore(); ok {
		_spec.AddField(scoreeditrequest.FieldNewHomeScore, field.TypeInt, value)
	}
	if value, ok := _u.mutation.NewAwayScore(); ok {
		_spec.SetField(scoreeditrequest.FieldNewAwayScore, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedNewAwayScore(); ok {
		_spec.AddField(scoreeditrequest.FieldNewAwayScore, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Reason(); ok {
		_spec.SetField(scoreeditrequest.FieldReason, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(scoreeditrequest.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.RejectionReason(); ok {
		_spec.SetField(scoreeditrequest.FieldRejectionReason, field.TypeString, value)
	}
	if _u.mutation.RejectionReasonCleared() {
		_spec.ClearField(scoreeditrequest.FieldRejectionReason, field.TypeString)
	}
	if value, ok := _u.mutation.ReviewedAt(); ok {
		_spec.SetField(scoreeditrequest.FieldReviewedAt, field.TypeTime, value)
	}
	if _u.mutation.ReviewedAtCleared() {
		_spec.ClearField(scoreeditrequest.FieldReviewedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(scoreeditrequest.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.PlayerScores(); ok {
		_spec.SetField(scoreeditrequest.FieldPlayerScores, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedPlayerScores(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, scoreeditrequest.FieldPlayerScores, value)
		})
	}
	if _u.mutation.PlayerScoresCleared() {
		_spec.ClearField(scoreeditrequest.FieldPlayerScores, field.TypeJSON)
	}
	if _u.mutation.GameCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   scoreeditrequest.GameTable,
			Columns: []string{scoreeditrequest.GameColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(game.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GameIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   scoreeditrequest.GameTable,
			Columns: []string{scoreeditrequest.GameColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(game.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RequestedByCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   scoreeditrequest.RequestedByTable,
			Columns: []string{scoreeditrequest.RequestedByColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RequestedByIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   scoreeditrequest.RequestedByTable,
			Columns: []string{scoreeditrequest.RequestedByColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ReviewedByCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   scoreeditrequest.ReviewedByTable,
			Columns: []string{scoreeditrequest.ReviewedByColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ReviewedByIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   scoreeditrequest.ReviewedByTable,
			Columns: []string{scoreeditrequest.ReviewedByColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{scoreeditrequest.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ScoreEditRequestUpdateOne is the builder for updating a single ScoreEditRequest entity.
type ScoreEditRequestUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ScoreEditRequestMutation
}

// SetGameID sets the "game_id" field.
func (_u *ScoreEditRequestUpdateOne) SetGameID(v uuid.UUID) *ScoreEditRequestUpdateOne {
	_u.mutation.SetGameID(v)
	return _u
}

// SetNillableGameID sets the "game_id" field if the given value is not nil.
func (_u *ScoreEditRequestUpdateOne) SetNillableGameID(v *uuid.UUID) *ScoreEditRequestUpdateOne {
	if v != nil {
		_u.SetGameID(*v)
	}
	return _u
}

// SetRequestedByID sets the "requested_by_id" field.
func (_u *ScoreEditRequestUpdateOne) SetRequestedByID(v uuid.UUID) *ScoreEditRequestUpdateOne {
	_u.mutation.SetRequestedByID(v)
	return _u
}

// SetNillableRequestedByID sets the "requested_by_id" field if the given value is not nil.
func (_u *ScoreEditRequestUpdateOne) SetNillableRequestedByID(v *uuid.UUID) *ScoreEditRequestUpdateOne {
	if v != nil {
		_u.SetRequestedByID(*v)
	}
	return _u
}

// SetPreviousHomeScore sets the "previous_home_score" field.
func (_u *ScoreEditRequestUpdateOne) SetPreviousHomeScore(v int) *ScoreEditRequestUpdateOne {
	_u.mutation.ResetPreviousHomeScore()
	_u.mutation.SetPreviousHomeScore(v)
	return _u
}

// SetNillablePreviousHomeScore sets the "previous_home_score" field if the given value is not nil.
func (_u *ScoreEditRequestUpdateOne) SetNillablePreviousHomeScore(v *int) *ScoreEditRequestUpdateOne {
	if v != nil {
		_u.SetPreviousHomeScore(*v)
	}
	return _u
}

// AddPreviousHomeScore adds value to the "previous_home_score" field.
func (_u *ScoreEditRequestUpdateOne) AddPreviousHomeScore(v int) *ScoreEditRequestUpdateOne {
	_u.mutation.AddPreviousHomeScore(v)
	return _u
}

// SetPreviousAwayScore sets the "previous_away_score" field.
func (_u *ScoreEditRequestUpdateOne) SetPreviousAwayScore(v int) *ScoreEditRequestUpdateOne {
	_u.mutation.ResetPreviousAwayScore()
	_u.mutation.SetPreviousAwayScore(v)
	return _u
}

// SetNillablePreviousAwayScore sets the "previous_away_score" field if the given value is not nil.
func (_u *ScoreEditRequestUpdateOne) SetNillablePreviousAwayScore(v *int) *ScoreEditRequestUpdateOne {
	if v != nil {
		_u.SetPreviousAwayScore(*v)
	}
	return _u
}

// AddPreviousAwayScore adds value to the "previous_away_score" field.
func (_u *ScoreEditRequestUpdateOne) AddPreviousAwayScore(v int) *ScoreEditRequestUpdateOne {
	_u.mutation.AddPreviousAwayScore(v)
	return _u
}

// SetNewHomeScore sets the "new_home_score" field.
func (_u *ScoreEditRequestUpdateOne) SetNewHomeScore(v int) *ScoreEditRequestUpdateOne {
	_u.mutation.ResetNewHomeScore()
	_u.mutation.SetNewHomeScore(v)
	return _u
}

// SetNillableNewHomeScore sets the "new_home_score" field if the given value is not nil.
func (_u *ScoreEditRequestUpdateOne) SetNillableNewHomeScore(v *int) *ScoreEditRequestUpdateOne {
	if v != nil {
		_u.SetNewHomeScore(*v)
	}
	return _u
}

// AddNewHomeScore adds value to the "new_home_score" field.
func (_u *ScoreEditRequestUpdateOne) AddNewHomeScore(v int) *ScoreEditRequestUpdateOne {
	_u.mutation.AddNewHomeScore(v)
	return _u
}

// SetNewAwayScore sets the "new_away_score" field.
func (_u *ScoreEditRequestUpdateOne) SetNewAwayScore(v int) *ScoreEditRequestUpdateOne {
	_u.mutation.ResetNewAwayScore()
	_u.mutation.SetNewAwayScore(v)
	return _u
}

// SetNillableNewAwayScore sets the "new_away_score" field if the given value is not nil.
func (_u *ScoreEditRequestUpdateOne) SetNillableNewAwayScore(v *int) *ScoreEditRequestUpdateOne {
	if v != nil {
		_u.SetNewAwayScore(*v)
	}
	return _u
}

// AddNewAwayScore adds value to the "new_away_score" field.
func (_u *ScoreEditRequestUpdateOne) AddNewAwayScore(v int) *ScoreEditRequestUpdateOne {
	_u.mutation.AddNewAwayScore(v)
	return _u
}

// SetReason sets the "reason" field.
func (_u *ScoreEditRequestUpdateOne) SetReason(v string) *ScoreEditRequestUpdateOne {
	_u.mutation.SetReason(v)
	return _u
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_u *ScoreEditRequestUpdateOne) SetNillableReason(v *string) *ScoreEditRequestUpdateOne {
	if v != nil {
		_u.SetReason(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *ScoreEditRequestUpdateOne) SetStatus(v string) *ScoreEditRequestUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ScoreEditRequestUpdateOne) SetNillableStatus(v *string) *ScoreEditRequestUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetRejectionReason sets the "rejection_reason" field.
func (_u *ScoreEditRequestUpdateOne) SetRejectionReason(v string) *ScoreEditRequestUpdateOne {
	_u.mutation.SetRejectionReason(v)
	return _u
}

// SetNillableRejectionReason sets the "rejection_reason" field if the given value is not nil.
func (_u *ScoreEditRequestUpdateOne) SetNillableRejectionReason(v *string) *ScoreEditRequestUpdateOne {
	if v != nil {
		_u.SetRejectionReason(*v)
	}
	return _u
}

// ClearRejectionReason clears the value of the "rejection_reason" field.
func (_u *ScoreEditRequestUpdateOne) ClearRejectionReason() *ScoreEditRequestUpdateOne {
	_u.mutation.ClearRejectionReason()
	return _u
}

// SetReviewedByID sets the "reviewed_by_id" field.
func (_u *ScoreEditRequestUpdateOne) SetReviewedByID(v uuid.UUID) *ScoreEditRequestUpdateOne {
	_u.mutation.SetReviewedByID(v)
	return _u
}

// SetNillableReviewedByID sets the "reviewed_by_id" field if the given value is not nil.
func (_u *ScoreEditRequestUpdateOne) SetNillableReviewedByID(v *uuid.UUID) *ScoreEditRequestUpdateOne {
	if v != nil {
		_u.SetReviewedByID(*v)
	}
	return _u
}

// ClearReviewedByID clears the value of the "reviewed_by_id" field.
func (_u *ScoreEditRequestUpdateOne) ClearReviewedByID() *ScoreEditRequestUpdateOne {
	_u.mutation.ClearReviewedByID()
	return _u
}

// SetReviewedAt sets the "reviewed_at" field.
func (_u *ScoreEditRequestUpdateOne) SetReviewedAt(v time.Time) *ScoreEditRequestUpdateOne {
	_u.mutation.SetReviewedAt(v)
	return _u
}

// SetNillableReviewedAt sets the "reviewed_at" field if the given value is not nil.
func (_u *ScoreEditRequestUpdateOne) SetNillableReviewedAt(v *time.Time) *ScoreEditRequestUpdateOne {
	if v != nil {
		_u.SetReviewedAt(*v)
	}
	return _u
}

// ClearReviewedAt clears the value of the "reviewed_at" field.
func (_u *ScoreEditRequestUpdateOne) ClearReviewedAt() *ScoreEditRequestUpdateOne {
	_u.mutation.ClearReviewedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ScoreEditRequestUpdateOne) SetUpdatedAt(v time.Time) *ScoreEditRequestUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetPlayerScores sets the "player_scores" field.
func (_u *ScoreEditRequestUpdateOne) SetPlayerScores(v []map[string]interface{}) *ScoreEditRequestUpdateOne {
	_u.mutation.SetPlayerScores(v)
	return _u
}

// AppendPlayerScores appends value to the "player_scores" field.
func (_u *ScoreEditRequestUpdateOne) AppendPlayerScores(v []map[string]interface{}) *ScoreEditRequestUpdateOne {
	_u.mutation.AppendPlayerScores(v)
	return _u
}

// ClearPlayerScores clears the value of the "player_scores" field.
func (_u *ScoreEditRequestUpdateOne) ClearPlayerScores() *ScoreEditRequestUpdateOne {
	_u.mutation.ClearPlayerScores()
	return _u
}

// SetGame sets the "game" edge to the Game entity.
func (_u *ScoreEditRequestUpdateOne) SetGame(v *Game) *ScoreEditRequestUpdateOne {
	return _u.SetGameID(v.ID)
}

// SetRequestedBy sets the "requested_by" edge to the User entity.
func (_u *ScoreEditRequestUpdateOne) SetRequestedBy(v *User) *ScoreEditRequestUpdateOne {
	return _u.SetRequestedByID(v.ID)
}

// SetReviewedBy sets the "reviewed_by" edge to the User entity.
func (_u *ScoreEditRequestUpdateOne) SetReviewedBy(v *User) *ScoreEditRequestUpdateOne {
	return _u.SetReviewedByID(v.ID)
}

// Mutation returns the ScoreEditRequestMutation object of the builder.
func (_u *ScoreEditRequestUpdateOne) Mutation() *ScoreEditRequestMutation {
	return _u.mutation
}

// ClearGame clears the "game" edge to the Game entity.
func (_u *ScoreEditRequestUpdateOne) ClearGame() *ScoreEditRequestUpdateOne {
	_u.mutation.ClearGame()
	return _u
}

// ClearRequestedBy clears the "requested_by" edge to the User entity.
func (_u *ScoreEditRequestUpdateOne) ClearRequestedBy() *ScoreEditRequestUpdateOne {
	_u.mutation.ClearRequestedBy()
	return _u
}

// ClearReviewedBy clears the "reviewed_by" edge to the User entity.
func (_u *ScoreEditRequestUpdateOne) ClearReviewedBy() *ScoreEditRequestUpdateOne {
	_u.mutation.ClearReviewedBy()
	return _u
}

// Where appends a list predicates to the ScoreEditRequestUpdate builder.
func (_u *ScoreEditRequestUpdateOne) Where(ps ...predicate.ScoreEditRequest) *ScoreEditRequestUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ScoreEditRequestUpdateOne) Select(field string, fields ...string) *ScoreEditRequestUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ScoreEditRequest entity.
func (_u *ScoreEditRequestUpdateOne) Save(ctx context.Context) (*ScoreEditRequest, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ScoreEditRequestUpdateOne) SaveX(ctx context.Context) *ScoreEditRequest {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ScoreEditRequestUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ScoreEditRequestUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ScoreEditRequestUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := scoreeditrequest.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ScoreEditRequestUpdateOne) check() error {
	if v, ok := _u.mutation.Reason(); ok {
		if err := scoreeditrequest.ReasonValidator(v); err != nil {
			return &ValidationError{Name: "reason", err: fmt.Errorf(`ent: validator failed for field "ScoreEditRequest.reason": %w`, err)}
		}
	}
	if _u.mutation.GameCleared() && len(_u.mutation.GameIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ScoreEditRequest.game"`)
	}
	if _u.mutation.RequestedByCleared() && len(_u.mutation.RequestedByIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ScoreEditRequest.requested_by"`)
	}
	return nil
}

func (_u *ScoreEditRequestUpdateOne) sqlSave(ctx context.Context) (_node *ScoreEditRequest, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(scoreeditrequest.Table, scoreeditrequest.Columns, sqlgraph.NewFieldSpec(scoreeditrequest.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ScoreEditRequest.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, scoreeditrequest.FieldID)
		for _, f := range fields {
			if !scoreeditrequest.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != scoreeditrequest.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.PreviousHomeScore(); ok {
		_spec.SetField(scoreeditrequest.FieldPreviousHomeScore, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPreviousHomeScore(); ok {
		_spec.AddField(scoreeditrequest.FieldPreviousHomeScore, field.TypeInt, value)
	}
	if value, ok := _u.mutation.PreviousAwayScore(); ok {
		_spec.SetField(scoreeditrequest.FieldPreviousAwayScore, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPreviousAwayScore(); ok {
		_spec.AddField(scoreeditrequest.FieldPreviousAwayScore, field.TypeInt, value)
	}
	if value, ok := _u.mutation.NewHomeScore(); ok {
		_spec.SetField(scoreeditrequest.FieldNewHomeScore, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedNewHomeScore(); ok {
		_spec.AddField(scoreeditrequest.FieldNewHomeScore, field.TypeInt, value)
	}
	if value, ok := _u.mutation.NewAwayScore(); ok {
		_spec.SetField(scoreeditrequest.FieldNewAwayScore, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedNewAwayScore(); ok {
		_spec.AddField(scoreeditrequest.FieldNewAwayScore, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Reason(); ok {
		_spec.SetField(scoreeditrequest.FieldReason, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(scoreeditrequest.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.RejectionReason(); ok {
		_spec.SetField(scoreeditrequest.FieldRejectionReason, field.TypeString, value)
	}
	if _u.mutation.RejectionReasonCleared() {
		_spec.ClearField(scoreeditrequest.FieldRejectionReason, field.TypeString)
	}
	if value, ok := _u.mutation.ReviewedAt(); ok {
		_spec.SetField(scoreeditrequest.FieldReviewedAt, field.TypeTime, value)
	}
	if _u.mutation.ReviewedAtCleared() {
		_spec.ClearField(scoreeditrequest.FieldReviewedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(scoreeditrequest.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.PlayerScores(); ok {
		_spec.SetField(scoreeditrequest.FieldPlayerScores, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedPlayerScores(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, scoreeditrequest.FieldPlayerScores, value)
		})
	}
	if _u.mutation.PlayerScoresCleared() {
		_spec.ClearField(scoreeditrequest.FieldPlayerScores, field.TypeJSON)
	}
	if _u.mutation.GameCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   scoreeditrequest.GameTable,
			Columns: []string{scoreeditrequest.GameColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(game.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GameIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   scoreeditrequest.GameTable,
			Columns: []string{scoreeditrequest.GameColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(game.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RequestedByCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   scoreeditrequest.RequestedByTable,
			Columns: []string{scoreeditrequest.RequestedByColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RequestedByIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   scoreeditrequest.RequestedByTable,
			Columns: []string{scoreeditrequest.RequestedByColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ReviewedByCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   scoreeditrequest.ReviewedByTable,
			Columns: []string{scoreeditrequest.ReviewedByColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ReviewedByIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   scoreeditrequest.ReviewedByTable,
			Columns: []string{scoreeditrequest.ReviewedByColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ScoreEditRequest{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{scoreeditrequest.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
