// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/game-stats-api/ent/player"
	"github.com/bengobox/game-stats-api/ent/predicate"
	"github.com/bengobox/game-stats-api/ent/spiritnomination"
	"github.com/bengobox/game-stats-api/ent/spiritscore"
	"github.com/google/uuid"
)

// SpiritNominationUpdate is the builder for updating SpiritNomination entities.
type SpiritNominationUpdate struct {
	config
	hooks    []Hook
	mutation *SpiritNominationMutation
}

// Where appends a list predicates to the SpiritNominationUpdate builder.
func (_u *SpiritNominationUpdate) Where(ps ...predicate.SpiritNomination) *SpiritNominationUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCategory sets the "category" field.
func (_u *SpiritNominationUpdate) SetCategory(v string) *SpiritNominationUpdate {
	_u.mutation.SetCategory(v)
	return _u
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_u *SpiritNominationUpdate) SetNillableCategory(v *string) *SpiritNominationUpdate {
	if v != nil {
		_u.SetCategory(*v)
	}
	return _u
}

// SetSpiritScoreID sets the "spirit_score" edge to the SpiritScore entity by ID.
func (_u *SpiritNominationUpdate) SetSpiritScoreID(id uuid.UUID) *SpiritNominationUpdate {
	_u.mutation.SetSpiritScoreID(id)
	return _u
}

// SetSpiritScore sets the "spirit_score" edge to the SpiritScore entity.
func (_u *SpiritNominationUpdate) SetSpiritScore(v *SpiritScore) *SpiritNominationUpdate {
	return _u.SetSpiritScoreID(v.ID)
}

// SetPlayerID sets the "player" edge to the Player entity by ID.
func (_u *SpiritNominationUpdate) SetPlayerID(id uuid.UUID) *SpiritNominationUpdate {
	_u.mutation.SetPlayerID(id)
	return _u
}

// SetPlayer sets the "player" edge to the Player entity.
func (_u *SpiritNominationUpdate) SetPlayer(v *Player) *SpiritNominationUpdate {
	return _u.SetPlayerID(v.ID)
}

// Mutation returns the SpiritNominationMutation object of the builder.
func (_u *SpiritNominationUpdate) Mutation() *SpiritNominationMutation {
	return _u.mutation
}

// ClearSpiritScore clears the "spirit_score" edge to the SpiritScore entity.
func (_u *SpiritNominationUpdate) ClearSpiritScore() *SpiritNominationUpdate {
	_u.mutation.ClearSpiritScore()
	return _u
}

// ClearPlayer clears the "player" edge to the Player entity.
func (_u *SpiritNominationUpdate) ClearPlayer() *SpiritNominationUpdate {
	_u.mutation.ClearPlayer()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SpiritNominationUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SpiritNominationUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SpiritNominationUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SpiritNominationUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SpiritNominationUpdate) check() error {
	if v, ok := _u.mutation.Category(); ok {
		if err := spiritnomination.CategoryValidator(v); err != nil {
			return &ValidationError{Name: "category", err: fmt.Errorf(`ent: validator failed for field "SpiritNomination.category": %w`, err)}
		}
	}
	if _u.mutation.SpiritScoreCleared() && len(_u.mutation.SpiritScoreIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SpiritNomination.spirit_score"`)
	}
	if _u.mutation.PlayerCleared() && len(_u.mutation.PlayerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SpiritNomination.player"`)
	}
	return nil
}

func (_u *SpiritNominationUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(spiritnomination.Table, spiritnomination.Columns, sqlgraph.NewFieldSpec(spiritnomination.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Category(); ok {
		_spec.SetField(spiritnomination.FieldCategory, field.TypeString, value)
	}
	if _u.mutation.SpiritScoreCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   spiritnomination.SpiritScoreTable,
			Columns: []string{spiritnomination.SpiritScoreColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(spiritscore.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SpiritScoreIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   spiritnomination.SpiritScoreTable,
			Columns: []string{spiritnomination.SpiritScoreColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(spiritscore.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PlayerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   spiritnomination.PlayerTable,
			Columns: []string{spiritnomination.PlayerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(player.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PlayerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   spiritnomination.PlayerTable,
			Columns: []string{spiritnomination.PlayerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(player.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{spiritnomination.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SpiritNominationUpdateOne is the builder for updating a single SpiritNomination entity.
type SpiritNominationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SpiritNominationMutation
}

// SetCategory sets the "category" field.
func (_u *SpiritNominationUpdateOne) SetCategory(v string) *SpiritNominationUpdateOne {
	_u.mutation.SetCategory(v)
	return _u
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_u *SpiritNominationUpdateOne) SetNillableCategory(v *string) *SpiritNominationUpdateOne {
	if v != nil {
		_u.SetCategory(*v)
	}
	return _u
}

// SetSpiritScoreID sets the "spirit_score" edge to the SpiritScore entity by ID.
func (_u *SpiritNominationUpdateOne) SetSpiritScoreID(id uuid.UUID) *SpiritNominationUpdateOne {
	_u.mutation.SetSpiritScoreID(id)
	return _u
}

// SetSpiritScore sets the "spirit_score" edge to the SpiritScore entity.
func (_u *SpiritNominationUpdateOne) SetSpiritScore(v *SpiritScore) *SpiritNominationUpdateOne {
	return _u.SetSpiritScoreID(v.ID)
}

// SetPlayerID sets the "player" edge to the Player entity by ID.
func (_u *SpiritNominationUpdateOne) SetPlayerID(id uuid.UUID) *SpiritNominationUpdateOne {
	_u.mutation.SetPlayerID(id)
	return _u
}

// SetPlayer sets the "player" edge to the Player entity.
func (_u *SpiritNominationUpdateOne) SetPlayer(v *Player) *SpiritNominationUpdateOne {
	return _u.SetPlayerID(v.ID)
}

// Mutation returns the SpiritNominationMutation object of the builder.
func (_u *SpiritNominationUpdateOne) Mutation() *SpiritNominationMutation {
	return _u.mutation
}

// ClearSpiritScore clears the "spirit_score" edge to the SpiritScore entity.
func (_u *SpiritNominationUpdateOne) ClearSpiritScore() *SpiritNominationUpdateOne {
	_u.mutation.ClearSpiritScore()
	return _u
}

// ClearPlayer clears the "player" edge to the Player entity.
func (_u *SpiritNominationUpdateOne) ClearPlayer() *SpiritNominationUpdateOne {
	_u.mutation.ClearPlayer()
	return _u
}

// Where appends a list predicates to the SpiritNominationUpdate builder.
func (_u *SpiritNominationUpdateOne) Where(ps ...predicate.SpiritNomination) *SpiritNominationUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SpiritNominationUpdateOne) Select(field string, fields ...string) *SpiritNominationUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SpiritNomination entity.
func (_u *SpiritNominationUpdateOne) Save(ctx context.Context) (*SpiritNomination, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SpiritNominationUpdateOne) SaveX(ctx context.Context) *SpiritNomination {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SpiritNominationUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SpiritNominationUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SpiritNominationUpdateOne) check() error {
	if v, ok := _u.mutation.Category(); ok {
		if err := spiritnomination.CategoryValidator(v); err != nil {
			return &ValidationError{Name: "category", err: fmt.Errorf(`ent: validator failed for field "SpiritNomination.category": %w`, err)}
		}
	}
	if _u.mutation.SpiritScoreCleared() && len(_u.mutation.SpiritScoreIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SpiritNomination.spirit_score"`)
	}
	if _u.mutation.PlayerCleared() && len(_u.mutation.PlayerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SpiritNomination.player"`)
	}
	return nil
}

func (_u *SpiritNominationUpdateOne) sqlSave(ctx context.Context) (_node *SpiritNomination, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(spiritnomination.Table, spiritnomination.Columns, sqlgraph.NewFieldSpec(spiritnomination.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SpiritNomination.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, spiritnomination.FieldID)
		for _, f := range fields {
			if !spiritnomination.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != spiritnomination.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Category(); ok {
		_spec.SetField(spiritnomination.FieldCategory, field.TypeString, value)
	}
	if _u.mutation.SpiritScoreCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   spiritnomination.SpiritScoreTable,
			Columns: []string{spiritnomination.SpiritScoreColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(spiritscore.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SpiritScoreIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   spiritnomination.SpiritScoreTable,
			Columns: []string{spiritnomination.SpiritScoreColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(spiritscore.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PlayerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   spiritnomination.PlayerTable,
			Columns: []string{spiritnomination.PlayerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(player.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PlayerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   spiritnomination.PlayerTable,
			Columns: []string{spiritnomination.PlayerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(player.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &SpiritNomination{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{spiritnomination.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
