// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/game-stats-api/ent/continent"
	"github.com/bengobox/game-stats-api/ent/country"
	"github.com/bengobox/game-stats-api/ent/discipline"
	"github.com/bengobox/game-stats-api/ent/event"
	"github.com/bengobox/game-stats-api/ent/game"
	"github.com/bengobox/game-stats-api/ent/predicate"
	"github.com/bengobox/game-stats-api/ent/scopedrole"
	"github.com/bengobox/game-stats-api/ent/scoreeditrequest"
	"github.com/bengobox/game-stats-api/ent/spiritscore"
	"github.com/bengobox/game-stats-api/ent/team"
	"github.com/bengobox/game-stats-api/ent/user"
	"github.com/google/uuid"
)

// UserUpdate is the builder for updating User entities.
type UserUpdate struct {
	config
	hooks    []Hook
	mutation *UserMutation
}

// Where appends a list predicates to the UserUpdate builder.
func (_u *UserUpdate) Where(ps ...predicate.User) *UserUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserUpdate) SetUpdatedAt(v time.Time) *UserUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *UserUpdate) SetDeletedAt(v time.Time) *UserUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *UserUpdate) SetNillableDeletedAt(v *time.Time) *UserUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *UserUpdate) ClearDeletedAt() *UserUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetEmail sets the "email" field.
func (_u *UserUpdate) SetEmail(v string) *UserUpdate {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *UserUpdate) SetNillableEmail(v *string) *UserUpdate {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetPasswordHash sets the "password_hash" field.
func (_u *UserUpdate) SetPasswordHash(v string) *UserUpdate {
	_u.mutation.SetPasswordHash(v)
	return _u
}

// SetNillablePasswordHash sets the "password_hash" field if the given value is not nil.
func (_u *UserUpdate) SetNillablePasswordHash(v *string) *UserUpdate {
	if v != nil {
		_u.SetPasswordHash(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *UserUpdate) SetName(v string) *UserUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *UserUpdate) SetNillableName(v *string) *UserUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetAvatarURL sets the "avatar_url" field.
func (_u *UserUpdate) SetAvatarURL(v string) *UserUpdate {
	_u.mutation.SetAvatarURL(v)
	return _u
}

// SetNillableAvatarURL sets the "avatar_url" field if the given value is not nil.
func (_u *UserUpdate) SetNillableAvatarURL(v *string) *UserUpdate {
	if v != nil {
		_u.SetAvatarURL(*v)
	}
	return _u
}

// ClearAvatarURL clears the value of the "avatar_url" field.
func (_u *UserUpdate) ClearAvatarURL() *UserUpdate {
	_u.mutation.ClearAvatarURL()
	return _u
}

// SetRole sets the "role" field.
func (_u *UserUpdate) SetRole(v string) *UserUpdate {
	_u.mutation.SetRole(v)
	return _u
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_u *UserUpdate) SetNillableRole(v *string) *UserUpdate {
	if v != nil {
		_u.SetRole(*v)
	}
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *UserUpdate) SetIsActive(v bool) *UserUpdate {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *UserUpdate) SetNillableIsActive(v *bool) *UserUpdate {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetLastLoginAt sets the "last_login_at" field.
func (_u *UserUpdate) SetLastLoginAt(v time.Time) *UserUpdate {
	_u.mutation.SetLastLoginAt(v)
	return _u
}

// SetNillableLastLoginAt sets the "last_login_at" field if the given value is not nil.
func (_u *UserUpdate) SetNillableLastLoginAt(v *time.Time) *UserUpdate {
	if v != nil {
		_u.SetLastLoginAt(*v)
	}
	return _u
}

// ClearLastLoginAt clears the value of the "last_login_at" field.
func (_u *UserUpdate) ClearLastLoginAt() *UserUpdate {
	_u.mutation.ClearLastLoginAt()
	return _u
}

// AddManagedContinentIDs adds the "managed_continent" edge to the Continent entity by IDs.
func (_u *UserUpdate) AddManagedContinentIDs(ids ...uuid.UUID) *UserUpdate {
	_u.mutation.AddManagedContinentIDs(ids...)
	return _u
}

// AddManagedContinent adds the "managed_continent" edges to the Continent entity.
func (_u *UserUpdate) AddManagedContinent(v ...*Continent) *UserUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddManagedContinentIDs(ids...)
}

// AddManagedCountryIDs adds the "managed_country" edge to the Country entity by IDs.
func (_u *UserUpdate) AddManagedCountryIDs(ids ...uuid.UUID) *UserUpdate {
	_u.mutation.AddManagedCountryIDs(ids...)
	return _u
}

// AddManagedCountry adds the "managed_country" edges to the Country entity.
func (_u *UserUpdate) AddManagedCountry(v ...*Country) *UserUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddManagedCountryIDs(ids...)
}

// AddManagedDisciplineIDs adds the "managed_discipline" edge to the Discipline entity by IDs.
func (_u *UserUpdate) AddManagedDisciplineIDs(ids ...uuid.UUID) *UserUpdate {
	_u.mutation.AddManagedDisciplineIDs(ids...)
	return _u
}

// AddManagedDiscipline adds the "managed_discipline" edges to the Discipline entity.
func (_u *UserUpdate) AddManagedDiscipline(v ...*Discipline) *UserUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddManagedDisciplineIDs(ids...)
}

// AddManagedEventIDs adds the "managed_event" edge to the Event entity by IDs.
func (_u *UserUpdate) AddManagedEventIDs(ids ...uuid.UUID) *UserUpdate {
	_u.mutation.AddManagedEventIDs(ids...)
	return _u
}

// AddManagedEvent adds the "managed_event" edges to the Event entity.
func (_u *UserUpdate) AddManagedEvent(v ...*Event) *UserUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddManagedEventIDs(ids...)
}

// AddManagedTeamIDs adds the "managed_team" edge to the Team entity by IDs.
func (_u *UserUpdate) AddManagedTeamIDs(ids ...uuid.UUID) *UserUpdate {
	_u.mutation.AddManagedTeamIDs(ids...)
	return _u
}

// AddManagedTeam adds the "managed_team" edges to the Team entity.
func (_u *UserUpdate) AddManagedTeam(v ...*Team) *UserUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddManagedTeamIDs(ids...)
}

// AddOfficiatedGameIDs adds the "officiated_games" edge to the Game entity by IDs.
func (_u *UserUpdate) AddOfficiatedGameIDs(ids ...uuid.UUID) *UserUpdate {
	_u.mutation.AddOfficiatedGameIDs(ids...)
	return _u
}

// AddOfficiatedGames adds the "officiated_games" edges to the Game entity.
func (_u *UserUpdate) AddOfficiatedGames(v ...*Game) *UserUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddOfficiatedGameIDs(ids...)
}

// AddScopedRoleIDs adds the "scoped_roles" edge to the ScopedRole entity by IDs.
func (_u *UserUpdate) AddScopedRoleIDs(ids ...uuid.UUID) *UserUpdate {
	_u.mutation.AddScopedRoleIDs(ids...)
	return _u
}

// AddScopedRoles adds the "scoped_roles" edges to the ScopedRole entity.
func (_u *UserUpdate) AddScopedRoles(v ...*ScopedRole) *UserUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddScopedRoleIDs(ids...)
}

// AddSubmittedSpiritScoreIDs adds the "submitted_spirit_scores" edge to the SpiritScore entity by IDs.
func (_u *UserUpdate) AddSubmittedSpiritScoreIDs(ids ...uuid.UUID) *UserUpdate {
	_u.mutation.AddSubmittedSpiritScoreIDs(ids...)
	return _u
}

// AddSubmittedSpiritScores adds the "submitted_spirit_scores" edges to the SpiritScore entity.
func (_u *UserUpdate) AddSubmittedSpiritScores(v ...*SpiritScore) *UserUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSubmittedSpiritScoreIDs(ids...)
}

// AddScoreEditRequestIDs adds the "score_edit_requests" edge to the ScoreEditRequest entity by IDs.
func (_u *UserUpdate) AddScoreEditRequestIDs(ids ...uuid.UUID) *UserUpdate {
	_u.mutation.AddScoreEditRequestIDs(ids...)
	return _u
}

// AddScoreEditRequests adds the "score_edit_requests" edges to the ScoreEditRequest entity.
func (_u *UserUpdate) AddScoreEditRequests(v ...*ScoreEditRequest) *UserUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddScoreEditRequestIDs(ids...)
}

// Mutation returns the UserMutation object of the builder.
func (_u *UserUpdate) Mutation() *UserMutation {
	return _u.mutation
}

// ClearManagedContinent clears all "managed_continent" edges to the Continent entity.
func (_u *UserUpdate) ClearManagedContinent() *UserUpdate {
	_u.mutation.ClearManagedContinent()
	return _u
}

// RemoveManagedContinentIDs removes the "managed_continent" edge to Continent entities by IDs.
func (_u *UserUpdate) RemoveManagedContinentIDs(ids ...uuid.UUID) *UserUpdate {
	_u.mutation.RemoveManagedContinentIDs(ids...)
	return _u
}

// RemoveManagedContinent removes "managed_continent" edges to Continent entities.
func (_u *UserUpdate) RemoveManagedContinent(v ...*Continent) *UserUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveManagedContinentIDs(ids...)
}

// ClearManagedCountry clears all "managed_country" edges to the Country entity.
func (_u *UserUpdate) ClearManagedCountry() *UserUpdate {
	_u.mutation.ClearManagedCountry()
	return _u
}

// RemoveManagedCountryIDs removes the "managed_country" edge to Country entities by IDs.
func (_u *UserUpdate) RemoveManagedCountryIDs(ids ...uuid.UUID) *UserUpdate {
	_u.mutation.RemoveManagedCountryIDs(ids...)
	return _u
}

// RemoveManagedCountry removes "managed_country" edges to Country entities.
func (_u *UserUpdate) RemoveManagedCountry(v ...*Country) *UserUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveManagedCountryIDs(ids...)
}

// ClearManagedDiscipline clears all "managed_discipline" edges to the Discipline entity.
func (_u *UserUpdate) ClearManagedDiscipline() *UserUpdate {
	_u.mutation.ClearManagedDiscipline()
	return _u
}

// RemoveManagedDisciplineIDs removes the "managed_discipline" edge to Discipline entities by IDs.
func (_u *UserUpdate) RemoveManagedDisciplineIDs(ids ...uuid.UUID) *UserUpdate {
	_u.mutation.RemoveManagedDisciplineIDs(ids...)
	return _u
}

// RemoveManagedDiscipline removes "managed_discipline" edges to Discipline entities.
func (_u *UserUpdate) RemoveManagedDiscipline(v ...*Discipline) *UserUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveManagedDisciplineIDs(ids...)
}

// ClearManagedEvent clears all "managed_event" edges to the Event entity.
func (_u *UserUpdate) ClearManagedEvent() *UserUpdate {
	_u.mutation.ClearManagedEvent()
	return _u
}

// RemoveManagedEventIDs removes the "managed_event" edge to Event entities by IDs.
func (_u *UserUpdate) RemoveManagedEventIDs(ids ...uuid.UUID) *UserUpdate {
	_u.mutation.RemoveManagedEventIDs(ids...)
	return _u
}

// RemoveManagedEvent removes "managed_event" edges to Event entities.
func (_u *UserUpdate) RemoveManagedEvent(v ...*Event) *UserUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveManagedEventIDs(ids...)
}

// ClearManagedTeam clears all "managed_team" edges to the Team entity.
func (_u *UserUpdate) ClearManagedTeam() *UserUpdate {
	_u.mutation.ClearManagedTeam()
	return _u
}

// RemoveManagedTeamIDs removes the "managed_team" edge to Team entities by IDs.
func (_u *UserUpdate) RemoveManagedTeamIDs(ids ...uuid.UUID) *UserUpdate {
	_u.mutation.RemoveManagedTeamIDs(ids...)
	return _u
}

// RemoveManagedTeam removes "managed_team" edges to Team entities.
func (_u *UserUpdate) RemoveManagedTeam(v ...*Team) *UserUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveManagedTeamIDs(ids...)
}

// ClearOfficiatedGames clears all "officiated_games" edges to the Game entity.
func (_u *UserUpdate) ClearOfficiatedGames() *UserUpdate {
	_u.mutation.ClearOfficiatedGames()
	return _u
}

// RemoveOfficiatedGameIDs removes the "officiated_games" edge to Game entities by IDs.
func (_u *UserUpdate) RemoveOfficiatedGameIDs(ids ...uuid.UUID) *UserUpdate {
	_u.mutation.RemoveOfficiatedGameIDs(ids...)
	return _u
}

// RemoveOfficiatedGames removes "officiated_games" edges to Game entities.
func (_u *UserUpdate) RemoveOfficiatedGames(v ...*Game) *UserUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveOfficiatedGameIDs(ids...)
}

// ClearScopedRoles clears all "scoped_roles" edges to the ScopedRole entity.
func (_u *UserUpdate) ClearScopedRoles() *UserUpdate {
	_u.mutation.ClearScopedRoles()
	return _u
}

// RemoveScopedRoleIDs removes the "scoped_roles" edge to ScopedRole entities by IDs.
func (_u *UserUpdate) RemoveScopedRoleIDs(ids ...uuid.UUID) *UserUpdate {
	_u.mutation.RemoveScopedRoleIDs(ids...)
	return _u
}

// RemoveScopedRoles removes "scoped_roles" edges to ScopedRole entities.
func (_u *UserUpdate) RemoveScopedRoles(v ...*ScopedRole) *UserUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveScopedRoleIDs(ids...)
}

// ClearSubmittedSpiritScores clears all "submitted_spirit_scores" edges to the SpiritScore entity.
func (_u *UserUpdate) ClearSubmittedSpiritScores() *UserUpdate {
	_u.mutation.ClearSubmittedSpiritScores()
	return _u
}

// RemoveSubmittedSpiritScoreIDs removes the "submitted_spirit_scores" edge to SpiritScore entities by IDs.
func (_u *UserUpdate) RemoveSubmittedSpiritScoreIDs(ids ...uuid.UUID) *UserUpdate {
	_u.mutation.RemoveSubmittedSpiritScoreIDs(ids...)
	return _u
}

// RemoveSubmittedSpiritScores removes "submitted_spirit_scores" edges to SpiritScore entities.
func (_u *UserUpdate) RemoveSubmittedSpiritScores(v ...*SpiritScore) *UserUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSubmittedSpiritScoreIDs(ids...)
}

// ClearScoreEditRequests clears all "score_edit_requests" edges to the ScoreEditRequest entity.
func (_u *UserUpdate) ClearScoreEditRequests() *UserUpdate {
	_u.mutation.ClearScoreEditRequests()
	return _u
}

// RemoveScoreEditRequestIDs removes the "score_edit_requests" edge to ScoreEditRequest entities by IDs.
func (_u *UserUpdate) RemoveScoreEditRequestIDs(ids ...uuid.UUID) *UserUpdate {
	_u.mutation.RemoveScoreEditRequestIDs(ids...)
	return _u
}

// RemoveScoreEditRequests removes "score_edit_requests" edges to ScoreEditRequest entities.
func (_u *UserUpdate) RemoveScoreEditRequests(v ...*ScoreEditRequest) *UserUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveScoreEditRequestIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := user.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserUpdate) check() error {
	if v, ok := _u.mutation.Email(); ok {
		if err := user.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "User.email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PasswordHash(); ok {
		if err := user.PasswordHashValidator(v); err != nil {
			return &ValidationError{Name: "password_hash", err: fmt.Errorf(`ent: validator failed for field "User.password_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := user.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "User.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Role(); ok {
		if err := user.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "User.role": %w`, err)}
		}
	}
	return nil
}

func (_u *UserUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(user.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(user.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(user.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(user.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.PasswordHash(); ok {
		_spec.SetField(user.FieldPasswordHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(user.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.AvatarURL(); ok {
		_spec.SetField(user.FieldAvatarURL, field.TypeString, value)
	}
	if _u.mutation.AvatarURLCleared() {
		_spec.ClearField(user.FieldAvatarURL, field.TypeString)
	}
	if value, ok := _u.mutation.Role(); ok {
		_spec.SetField(user.FieldRole, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(user.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.LastLoginAt(); ok {
		_spec.SetField(user.FieldLastLoginAt, field.TypeTime, value)
	}
	if _u.mutation.LastLoginAtCleared() {
		_spec.ClearField(user.FieldLastLoginAt, field.TypeTime)
	}
	if _u.mutation.ManagedContinentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   user.ManagedContinentTable,
			Columns: user.ManagedContinentPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(continent.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedManagedContinentIDs(); len(nodes) > 0 && !_u.mutation.ManagedContinentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   user.ManagedContinentTable,
			Columns: user.ManagedContinentPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(continent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ManagedContinentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   user.ManagedContinentTable,
			Columns: user.ManagedContinentPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(continent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ManagedCountryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   user.ManagedCountryTable,
			Columns: user.ManagedCountryPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(country.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedManagedCountryIDs(); len(nodes) > 0 && !_u.mutation.ManagedCountryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   user.ManagedCountryTable,
			Columns: user.ManagedCountryPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(country.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ManagedCountryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   user.ManagedCountryTable,
			Columns: user.ManagedCountryPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(country.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ManagedDisciplineCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   user.ManagedDisciplineTable,
			Columns: user.ManagedDisciplinePrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(discipline.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedManagedDisciplineIDs(); len(nodes) > 0 && !_u.mutation.ManagedDisciplineCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   user.ManagedDisciplineTable,
			Columns: user.ManagedDisciplinePrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(discipline.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ManagedDisciplineIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   user.ManagedDisciplineTable,
			Columns: user.ManagedDisciplinePrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(discipline.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ManagedEventCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   user.ManagedEventTable,
			Columns: user.ManagedEventPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedManagedEventIDs(); len(nodes) > 0 && !_u.mutation.ManagedEventCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   user.ManagedEventTable,
			Columns: user.ManagedEventPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ManagedEventIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   user.ManagedEventTable,
			Columns: user.ManagedEventPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ManagedTeamCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   user.ManagedTeamTable,
			Columns: user.ManagedTeamPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedManagedTeamIDs(); len(nodes) > 0 && !_u.mutation.ManagedTeamCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   user.ManagedTeamTable,
			Columns: user.ManagedTeamPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ManagedTeamIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   user.ManagedTeamTable,
			Columns: user.ManagedTeamPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.OfficiatedGamesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.OfficiatedGamesTable,
			Columns: []string{user.OfficiatedGamesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(game.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedOfficiatedGamesIDs(); len(nodes) > 0 && !_u.mutation.OfficiatedGamesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.OfficiatedGamesTable,
			Columns: []string{user.OfficiatedGamesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(game.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OfficiatedGamesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.OfficiatedGamesTable,
			Columns: []string{user.OfficiatedGamesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(game.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ScopedRolesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ScopedRolesTable,
			Columns: []string{user.ScopedRolesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(scopedrole.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedScopedRolesIDs(); len(nodes) > 0 && !_u.mutation.ScopedRolesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ScopedRolesTable,
			Columns: []string{user.ScopedRolesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(scopedrole.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ScopedRolesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ScopedRolesTable,
			Columns: []string{user.ScopedRolesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(scopedrole.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SubmittedSpiritScoresCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.SubmittedSpiritScoresTable,
			Columns: []string{user.SubmittedSpiritScoresColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(spiritscore.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSubmittedSpiritScoresIDs(); len(nodes) > 0 && !_u.mutation.SubmittedSpiritScoresCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.SubmittedSpiritScoresTable,
			Columns: []string{user.SubmittedSpiritScoresColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(spiritscore.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SubmittedSpiritScoresIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.SubmittedSpiritScoresTable,
			Columns: []string{user.SubmittedSpiritScoresColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(spiritscore.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ScoreEditRequestsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ScoreEditRequestsTable,
			Columns: []string{user.ScoreEditRequestsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(scoreeditrequest.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedScoreEditRequestsIDs(); len(nodes) > 0 && !_u.mutation.ScoreEditRequestsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ScoreEditRequestsTable,
			Columns: []string{user.ScoreEditRequestsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(scoreeditrequest.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ScoreEditRequestsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ScoreEditRequestsTable,
			Columns: []string{user.ScoreEditRequestsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(scoreeditrequest.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserUpdateOne is the builder for updating a single User entity.
type UserUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserUpdateOne) SetUpdatedAt(v time.Time) *UserUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *UserUpdateOne) SetDeletedAt(v time.Time) *UserUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableDeletedAt(v *time.Time) *UserUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *UserUpdateOne) ClearDeletedAt() *UserUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetEmail sets the "email" field.
func (_u *UserUpdateOne) SetEmail(v string) *UserUpdateOne {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableEmail(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetPasswordHash sets the "password_hash" field.
func (_u *UserUpdateOne) SetPasswordHash(v string) *UserUpdateOne {
	_u.mutation.SetPasswordHash(v)
	return _u
}

// SetNillablePasswordHash sets the "password_hash" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillablePasswordHash(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetPasswordHash(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *UserUpdateOne) SetName(v string) *UserUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableName(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetAvatarURL sets the "avatar_url" field.
func (_u *UserUpdateOne) SetAvatarURL(v string) *UserUpdateOne {
	_u.mutation.SetAvatarURL(v)
	return _u
}

// SetNillableAvatarURL sets the "avatar_url" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableAvatarURL(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetAvatarURL(*v)
	}
	return _u
}

// ClearAvatarURL clears the value of the "avatar_url" field.
func (_u *UserUpdateOne) ClearAvatarURL() *UserUpdateOne {
	_u.mutation.ClearAvatarURL()
	return _u
}

// SetRole sets the "role" field.
func (_u *UserUpdateOne) SetRole(v string) *UserUpdateOne {
	_u.mutation.SetRole(v)
	return _u
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableRole(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetRole(*v)
	}
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *UserUpdateOne) SetIsActive(v bool) *UserUpdateOne {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableIsActive(v *bool) *UserUpdateOne {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetLastLoginAt sets the "last_login_at" field.
func (_u *UserUpdateOne) SetLastLoginAt(v time.Time) *UserUpdateOne {
	_u.mutation.SetLastLoginAt(v)
	return _u
}

// SetNillableLastLoginAt sets the "last_login_at" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableLastLoginAt(v *time.Time) *UserUpdateOne {
	if v != nil {
		_u.SetLastLoginAt(*v)
	}
	return _u
}

// ClearLastLoginAt clears the value of the "last_login_at" field.
func (_u *UserUpdateOne) ClearLastLoginAt() *UserUpdateOne {
	_u.mutation.ClearLastLoginAt()
	return _u
}

// AddManagedContinentIDs adds the "managed_continent" edge to the Continent entity by IDs.
func (_u *UserUpdateOne) AddManagedContinentIDs(ids ...uuid.UUID) *UserUpdateOne {
	_u.mutation.AddManagedContinentIDs(ids...)
	return _u
}

// AddManagedContinent adds the "managed_continent" edges to the Continent entity.
func (_u *UserUpdateOne) AddManagedContinent(v ...*Continent) *UserUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddManagedContinentIDs(ids...)
}

// AddManagedCountryIDs adds the "managed_country" edge to the Country entity by IDs.
func (_u *UserUpdateOne) AddManagedCountryIDs(ids ...uuid.UUID) *UserUpdateOne {
	_u.mutation.AddManagedCountryIDs(ids...)
	return _u
}

// AddManagedCountry adds the "managed_country" edges to the Country entity.
func (_u *UserUpdateOne) AddManagedCountry(v ...*Country) *UserUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddManagedCountryIDs(ids...)
}

// AddManagedDisciplineIDs adds the "managed_discipline" edge to the Discipline entity by IDs.
func (_u *UserUpdateOne) AddManagedDisciplineIDs(ids ...uuid.UUID) *UserUpdateOne {
	_u.mutation.AddManagedDisciplineIDs(ids...)
	return _u
}

// AddManagedDiscipline adds the "managed_discipline" edges to the Discipline entity.
func (_u *UserUpdateOne) AddManagedDiscipline(v ...*Discipline) *UserUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddManagedDisciplineIDs(ids...)
}

// AddManagedEventIDs adds the "managed_event" edge to the Event entity by IDs.
func (_u *UserUpdateOne) AddManagedEventIDs(ids ...uuid.UUID) *UserUpdateOne {
	_u.mutation.AddManagedEventIDs(ids...)
	return _u
}

// AddManagedEvent adds the "managed_event" edges to the Event entity.
func (_u *UserUpdateOne) AddManagedEvent(v ...*Event) *UserUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddManagedEventIDs(ids...)
}

// AddManagedTeamIDs adds the "managed_team" edge to the Team entity by IDs.
func (_u *UserUpdateOne) AddManagedTeamIDs(ids ...uuid.UUID) *UserUpdateOne {
	_u.mutation.AddManagedTeamIDs(ids...)
	return _u
}

// AddManagedTeam adds the "managed_team" edges to the Team entity.
func (_u *UserUpdateOne) AddManagedTeam(v ...*Team) *UserUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddManagedTeamIDs(ids...)
}

// AddOfficiatedGameIDs adds the "officiated_games" edge to the Game entity by IDs.
func (_u *UserUpdateOne) AddOfficiatedGameIDs(ids ...uuid.UUID) *UserUpdateOne {
	_u.mutation.AddOfficiatedGameIDs(ids...)
	return _u
}

// AddOfficiatedGames adds the "officiated_games" edges to the Game entity.
func (_u *UserUpdateOne) AddOfficiatedGames(v ...*Game) *UserUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddOfficiatedGameIDs(ids...)
}

// AddScopedRoleIDs adds the "scoped_roles" edge to the ScopedRole entity by IDs.
func (_u *UserUpdateOne) AddScopedRoleIDs(ids ...uuid.UUID) *UserUpdateOne {
	_u.mutation.AddScopedRoleIDs(ids...)
	return _u
}

// AddScopedRoles adds the "scoped_roles" edges to the ScopedRole entity.
func (_u *UserUpdateOne) AddScopedRoles(v ...*ScopedRole) *UserUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddScopedRoleIDs(ids...)
}

// AddSubmittedSpiritScoreIDs adds the "submitted_spirit_scores" edge to the SpiritScore entity by IDs.
func (_u *UserUpdateOne) AddSubmittedSpiritScoreIDs(ids ...uuid.UUID) *UserUpdateOne {
	_u.mutation.AddSubmittedSpiritScoreIDs(ids...)
	return _u
}

// AddSubmittedSpiritScores adds the "submitted_spirit_scores" edges to the SpiritScore entity.
func (_u *UserUpdateOne) AddSubmittedSpiritScores(v ...*SpiritScore) *UserUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSubmittedSpiritScoreIDs(ids...)
}

// AddScoreEditRequestIDs adds the "score_edit_requests" edge to the ScoreEditRequest entity by IDs.
func (_u *UserUpdateOne) AddScoreEditRequestIDs(ids ...uuid.UUID) *UserUpdateOne {
	_u.mutation.AddScoreEditRequestIDs(ids...)
	return _u
}

// AddScoreEditRequests adds the "score_edit_requests" edges to the ScoreEditRequest entity.
func (_u *UserUpdateOne) AddScoreEditRequests(v ...*ScoreEditRequest) *UserUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddScoreEditRequestIDs(ids...)
}

// Mutation returns the UserMutation object of the builder.
func (_u *UserUpdateOne) Mutation() *UserMutation {
	return _u.mutation
}

// ClearManagedContinent clears all "managed_continent" edges to the Continent entity.
func (_u *UserUpdateOne) ClearManagedContinent() *UserUpdateOne {
	_u.mutation.ClearManagedContinent()
	return _u
}

// RemoveManagedContinentIDs removes the "managed_continent" edge to Continent entities by IDs.
func (_u *UserUpdateOne) RemoveManagedContinentIDs(ids ...uuid.UUID) *UserUpdateOne {
	_u.mutation.RemoveManagedContinentIDs(ids...)
	return _u
}

// RemoveManagedContinent removes "managed_continent" edges to Continent entities.
func (_u *UserUpdateOne) RemoveManagedContinent(v ...*Continent) *UserUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveManagedContinentIDs(ids...)
}

// ClearManagedCountry clears all "managed_country" edges to the Country entity.
func (_u *UserUpdateOne) ClearManagedCountry() *UserUpdateOne {
	_u.mutation.ClearManagedCountry()
	return _u
}

// RemoveManagedCountryIDs removes the "managed_country" edge to Country entities by IDs.
func (_u *UserUpdateOne) RemoveManagedCountryIDs(ids ...uuid.UUID) *UserUpdateOne {
	_u.mutation.RemoveManagedCountryIDs(ids...)
	return _u
}

// RemoveManagedCountry removes "managed_country" edges to Country entities.
func (_u *UserUpdateOne) RemoveManagedCountry(v ...*Country) *UserUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveManagedCountryIDs(ids...)
}

// ClearManagedDiscipline clears all "managed_discipline" edges to the Discipline entity.
func (_u *UserUpdateOne) ClearManagedDiscipline() *UserUpdateOne {
	_u.mutation.ClearManagedDiscipline()
	return _u
}

// RemoveManagedDisciplineIDs removes the "managed_discipline" edge to Discipline entities by IDs.
func (_u *UserUpdateOne) RemoveManagedDisciplineIDs(ids ...uuid.UUID) *UserUpdateOne {
	_u.mutation.RemoveManagedDisciplineIDs(ids...)
	return _u
}

// RemoveManagedDiscipline removes "managed_discipline" edges to Discipline entities.
func (_u *UserUpdateOne) RemoveManagedDiscipline(v ...*Discipline) *UserUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveManagedDisciplineIDs(ids...)
}

// ClearManagedEvent clears all "managed_event" edges to the Event entity.
func (_u *UserUpdateOne) ClearManagedEvent() *UserUpdateOne {
	_u.mutation.ClearManagedEvent()
	return _u
}

// RemoveManagedEventIDs removes the "managed_event" edge to Event entities by IDs.
func (_u *UserUpdateOne) RemoveManagedEventIDs(ids ...uuid.UUID) *UserUpdateOne {
	_u.mutation.RemoveManagedEventIDs(ids...)
	return _u
}

// RemoveManagedEvent removes "managed_event" edges to Event entities.
func (_u *UserUpdateOne) RemoveManagedEvent(v ...*Event) *UserUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveManagedEventIDs(ids...)
}

// ClearManagedTeam clears all "managed_team" edges to the Team entity.
func (_u *UserUpdateOne) ClearManagedTeam() *UserUpdateOne {
	_u.mutation.ClearManagedTeam()
	return _u
}

// RemoveManagedTeamIDs removes the "managed_team" edge to Team entities by IDs.
func (_u *UserUpdateOne) RemoveManagedTeamIDs(ids ...uuid.UUID) *UserUpdateOne {
	_u.mutation.RemoveManagedTeamIDs(ids...)
	return _u
}

// RemoveManagedTeam removes "managed_team" edges to Team entities.
func (_u *UserUpdateOne) RemoveManagedTeam(v ...*Team) *UserUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveManagedTeamIDs(ids...)
}

// ClearOfficiatedGames clears all "officiated_games" edges to the Game entity.
func (_u *UserUpdateOne) ClearOfficiatedGames() *UserUpdateOne {
	_u.mutation.ClearOfficiatedGames()
	return _u
}

// RemoveOfficiatedGameIDs removes the "officiated_games" edge to Game entities by IDs.
func (_u *UserUpdateOne) RemoveOfficiatedGameIDs(ids ...uuid.UUID) *UserUpdateOne {
	_u.mutation.RemoveOfficiatedGameIDs(ids...)
	return _u
}

// RemoveOfficiatedGames removes "officiated_games" edges to Game entities.
func (_u *UserUpdateOne) RemoveOfficiatedGames(v ...*Game) *UserUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveOfficiatedGameIDs(ids...)
}

// ClearScopedRoles clears all "scoped_roles" edges to the ScopedRole entity.
func (_u *UserUpdateOne) ClearScopedRoles() *UserUpdateOne {
	_u.mutation.ClearScopedRoles()
	return _u
}

// RemoveScopedRoleIDs removes the "scoped_roles" edge to ScopedRole entities by IDs.
func (_u *UserUpdateOne) RemoveScopedRoleIDs(ids ...uuid.UUID) *UserUpdateOne {
	_u.mutation.RemoveScopedRoleIDs(ids...)
	return _u
}

// RemoveScopedRoles removes "scoped_roles" edges to ScopedRole entities.
func (_u *UserUpdateOne) RemoveScopedRoles(v ...*ScopedRole) *UserUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveScopedRoleIDs(ids...)
}

// ClearSubmittedSpiritScores clears all "submitted_spirit_scores" edges to the SpiritScore entity.
func (_u *UserUpdateOne) ClearSubmittedSpiritScores() *UserUpdateOne {
	_u.mutation.ClearSubmittedSpiritScores()
	return _u
}

// RemoveSubmittedSpiritScoreIDs removes the "submitted_spirit_scores" edge to SpiritScore entities by IDs.
func (_u *UserUpdateOne) RemoveSubmittedSpiritScoreIDs(ids ...uuid.UUID) *UserUpdateOne {
	_u.mutation.RemoveSubmittedSpiritScoreIDs(ids...)
	return _u
}

// RemoveSubmittedSpiritScores removes "submitted_spirit_scores" edges to SpiritScore entities.
func (_u *UserUpdateOne) RemoveSubmittedSpiritScores(v ...*SpiritScore) *UserUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSubmittedSpiritScoreIDs(ids...)
}

// ClearScoreEditRequests clears all "score_edit_requests" edges to the ScoreEditRequest entity.
func (_u *UserUpdateOne) ClearScoreEditRequests() *UserUpdateOne {
	_u.mutation.ClearScoreEditRequests()
	return _u
}

// RemoveScoreEditRequestIDs removes the "score_edit_requests" edge to ScoreEditRequest entities by IDs.
func (_u *UserUpdateOne) RemoveScoreEditRequestIDs(ids ...uuid.UUID) *UserUpdateOne {
	_u.mutation.RemoveScoreEditRequestIDs(ids...)
	return _u
}

// RemoveScoreEditRequests removes "score_edit_requests" edges to ScoreEditRequest entities.
func (_u *UserUpdateOne) RemoveScoreEditRequests(v ...*ScoreEditRequest) *UserUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveScoreEditRequestIDs(ids...)
}

// Where appends a list predicates to the UserUpdate builder.
func (_u *UserUpdateOne) Where(ps ...predicate.User) *UserUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserUpdateOne) Select(field string, fields ...string) *UserUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated User entity.
func (_u *UserUpdateOne) Save(ctx context.Context) (*User, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserUpdateOne) SaveX(ctx context.Context) *User {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := user.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserUpdateOne) check() error {
	if v, ok := _u.mutation.Email(); ok {
		if err := user.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "User.email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PasswordHash(); ok {
		if err := user.PasswordHashValidator(v); err != nil {
			return &ValidationError{Name: "password_hash", err: fmt.Errorf(`ent: validator failed for field "User.password_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := user.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "User.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Role(); ok {
		if err := user.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "User.role": %w`, err)}
		}
	}
	return nil
}

func (_u *UserUpdateOne) sqlSave(ctx context.Context) (_node *User, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "User.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, user.FieldID)
		for _, f := range fields {
			if !user.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != user.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(user.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(user.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(user.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(user.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.PasswordHash(); ok {
		_spec.SetField(user.FieldPasswordHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(user.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.AvatarURL(); ok {
		_spec.SetField(user.FieldAvatarURL, field.TypeString, value)
	}
	if _u.mutation.AvatarURLCleared() {
		_spec.ClearField(user.FieldAvatarURL, field.TypeString)
	}
	if value, ok := _u.mutation.Role(); ok {
		_spec.SetField(user.FieldRole, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(user.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.LastLoginAt(); ok {
		_spec.SetField(user.FieldLastLoginAt, field.TypeTime, value)
	}
	if _u.mutation.LastLoginAtCleared() {
		_spec.ClearField(user.FieldLastLoginAt, field.TypeTime)
	}
	if _u.mutation.ManagedContinentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   user.ManagedContinentTable,
			Columns: user.ManagedContinentPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(continent.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedManagedContinentIDs(); len(nodes) > 0 && !_u.mutation.ManagedContinentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   user.ManagedContinentTable,
			Columns: user.ManagedContinentPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(continent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ManagedContinentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   user.ManagedContinentTable,
			Columns: user.ManagedContinentPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(continent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ManagedCountryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   user.ManagedCountryTable,
			Columns: user.ManagedCountryPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(country.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedManagedCountryIDs(); len(nodes) > 0 && !_u.mutation.ManagedCountryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   user.ManagedCountryTable,
			Columns: user.ManagedCountryPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(country.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ManagedCountryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   user.ManagedCountryTable,
			Columns: user.ManagedCountryPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(country.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ManagedDisciplineCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   user.ManagedDisciplineTable,
			Columns: user.ManagedDisciplinePrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(discipline.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedManagedDisciplineIDs(); len(nodes) > 0 && !_u.mutation.ManagedDisciplineCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   user.ManagedDisciplineTable,
			Columns: user.ManagedDisciplinePrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(discipline.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ManagedDisciplineIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   user.ManagedDisciplineTable,
			Columns: user.ManagedDisciplinePrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(discipline.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ManagedEventCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   user.ManagedEventTable,
			Columns: user.ManagedEventPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedManagedEventIDs(); len(nodes) > 0 && !_u.mutation.ManagedEventCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   user.ManagedEventTable,
			Columns: user.ManagedEventPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ManagedEventIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   user.ManagedEventTable,
			Columns: user.ManagedEventPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ManagedTeamCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   user.ManagedTeamTable,
			Columns: user.ManagedTeamPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedManagedTeamIDs(); len(nodes) > 0 && !_u.mutation.ManagedTeamCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   user.ManagedTeamTable,
			Columns: user.ManagedTeamPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ManagedTeamIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   user.ManagedTeamTable,
			Columns: user.ManagedTeamPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.OfficiatedGamesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.OfficiatedGamesTable,
			Columns: []string{user.OfficiatedGamesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(game.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedOfficiatedGamesIDs(); len(nodes) > 0 && !_u.mutation.OfficiatedGamesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.OfficiatedGamesTable,
			Columns: []string{user.OfficiatedGamesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(game.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OfficiatedGamesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.OfficiatedGamesTable,
			Columns: []string{user.OfficiatedGamesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(game.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ScopedRolesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ScopedRolesTable,
			Columns: []string{user.ScopedRolesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(scopedrole.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedScopedRolesIDs(); len(nodes) > 0 && !_u.mutation.ScopedRolesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ScopedRolesTable,
			Columns: []string{user.ScopedRolesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(scopedrole.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ScopedRolesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ScopedRolesTable,
			Columns: []string{user.ScopedRolesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(scopedrole.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SubmittedSpiritScoresCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.SubmittedSpiritScoresTable,
			Columns: []string{user.SubmittedSpiritScoresColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(spiritscore.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSubmittedSpiritScoresIDs(); len(nodes) > 0 && !_u.mutation.SubmittedSpiritScoresCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.SubmittedSpiritScoresTable,
			Columns: []string{user.SubmittedSpiritScoresColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(spiritscore.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SubmittedSpiritScoresIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.SubmittedSpiritScoresTable,
			Columns: []string{user.SubmittedSpiritScoresColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(spiritscore.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ScoreEditRequestsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ScoreEditRequestsTable,
			Columns: []string{user.ScoreEditRequestsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(scoreeditrequest.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedScoreEditRequestsIDs(); len(nodes) > 0 && !_u.mutation.ScoreEditRequestsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ScoreEditRequestsTable,
			Columns: []string{user.ScoreEditRequestsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(scoreeditrequest.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ScoreEditRequestsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ScoreEditRequestsTable,
			Columns: []string{user.ScoreEditRequestsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(scoreeditrequest.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &User{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
