-- Create "analytics_embeddings" table
CREATE TABLE "analytics_embeddings" ("id" uuid NOT NULL, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, "deleted_at" timestamptz NULL, "entity_type" character varying NOT NULL, "entity_id" uuid NOT NULL, "embedding" jsonb NULL, "content" text NULL, "metadata" jsonb NULL, PRIMARY KEY ("id"));
-- Create "audit_logs" table
CREATE TABLE "audit_logs" ("id" uuid NOT NULL, "entity_type" character varying NOT NULL, "entity_id" uuid NOT NULL, "action" character varying NOT NULL, "user_id" uuid NOT NULL, "username" character varying NOT NULL, "changes" jsonb NOT NULL, "reason" text NOT NULL, "ip_address" character varying NULL, "user_agent" text NULL, "created_at" timestamptz NOT NULL, PRIMARY KEY ("id"));
-- Create index "auditlog_created_at" to table: "audit_logs"
CREATE INDEX "auditlog_created_at" ON "audit_logs" ("created_at");
-- Create index "auditlog_entity_type_entity_id" to table: "audit_logs"
CREATE INDEX "auditlog_entity_type_entity_id" ON "audit_logs" ("entity_type", "entity_id");
-- Create index "auditlog_user_id" to table: "audit_logs"
CREATE INDEX "auditlog_user_id" ON "audit_logs" ("user_id");
-- Create "analytic_searches" table
CREATE TABLE "analytic_searches" ("id" uuid NOT NULL, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, "deleted_at" timestamptz NULL, "query" text NOT NULL, "explanation" text NULL, "generated_sql" text NULL, "metadata" jsonb NULL, PRIMARY KEY ("id"));
-- Create "worlds" table
CREATE TABLE "worlds" ("id" uuid NOT NULL, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, "deleted_at" timestamptz NULL, "name" character varying NOT NULL, "slug" character varying NOT NULL, "description" text NULL, PRIMARY KEY ("id"));
-- Create index "worlds_name_key" to table: "worlds"
CREATE UNIQUE INDEX "worlds_name_key" ON "worlds" ("name");
-- Create index "worlds_slug_key" to table: "worlds"
CREATE UNIQUE INDEX "worlds_slug_key" ON "worlds" ("slug");
-- Create "continents" table
CREATE TABLE "continents" ("id" uuid NOT NULL, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, "deleted_at" timestamptz NULL, "name" character varying NOT NULL, "slug" character varying NOT NULL, "description" text NULL, "world_id" uuid NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "continents_worlds_continents" FOREIGN KEY ("world_id") REFERENCES "worlds" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- Create index "continents_slug_key" to table: "continents"
CREATE UNIQUE INDEX "continents_slug_key" ON "continents" ("slug");
-- Create "users" table
CREATE TABLE "users" ("id" uuid NOT NULL, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, "deleted_at" timestamptz NULL, "email" character varying NOT NULL, "password_hash" character varying NOT NULL, "name" character varying NOT NULL, "avatar_url" character varying NULL, "role" character varying NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "last_login_at" timestamptz NULL, PRIMARY KEY ("id"));
-- Create index "users_email_key" to table: "users"
CREATE UNIQUE INDEX "users_email_key" ON "users" ("email");
-- Create "continent_managed_by" table
CREATE TABLE "continent_managed_by" ("continent_id" uuid NOT NULL, "user_id" uuid NOT NULL, PRIMARY KEY ("continent_id", "user_id"), CONSTRAINT "continent_managed_by_continent_id" FOREIGN KEY ("continent_id") REFERENCES "continents" ("id") ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT "continent_managed_by_user_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
-- Create "countries" table
CREATE TABLE "countries" ("id" uuid NOT NULL, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, "deleted_at" timestamptz NULL, "name" character varying NOT NULL, "slug" character varying NOT NULL, "code" character varying NOT NULL, "description" text NULL, "continent_id" uuid NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "countries_continents_countries" FOREIGN KEY ("continent_id") REFERENCES "continents" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- Create index "countries_code_key" to table: "countries"
CREATE UNIQUE INDEX "countries_code_key" ON "countries" ("code");
-- Create index "countries_slug_key" to table: "countries"
CREATE UNIQUE INDEX "countries_slug_key" ON "countries" ("slug");
-- Create "country_managed_by" table
CREATE TABLE "country_managed_by" ("country_id" uuid NOT NULL, "user_id" uuid NOT NULL, PRIMARY KEY ("country_id", "user_id"), CONSTRAINT "country_managed_by_country_id" FOREIGN KEY ("country_id") REFERENCES "countries" ("id") ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT "country_managed_by_user_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
-- Create "disciplines" table
CREATE TABLE "disciplines" ("id" uuid NOT NULL, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, "deleted_at" timestamptz NULL, "name" character varying NOT NULL, "slug" character varying NOT NULL, "description" text NULL, "rules_pdf_url" character varying NULL, "country_disciplines" uuid NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "disciplines_countries_disciplines" FOREIGN KEY ("country_disciplines") REFERENCES "countries" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- Create index "disciplines_slug_key" to table: "disciplines"
CREATE UNIQUE INDEX "disciplines_slug_key" ON "disciplines" ("slug");
-- Create "discipline_managed_by" table
CREATE TABLE "discipline_managed_by" ("discipline_id" uuid NOT NULL, "user_id" uuid NOT NULL, PRIMARY KEY ("discipline_id", "user_id"), CONSTRAINT "discipline_managed_by_discipline_id" FOREIGN KEY ("discipline_id") REFERENCES "disciplines" ("id") ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT "discipline_managed_by_user_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
-- Create "locations" table
CREATE TABLE "locations" ("id" uuid NOT NULL, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, "deleted_at" timestamptz NULL, "name" character varying NOT NULL, "slug" character varying NOT NULL, "address" character varying NULL, "city" character varying NULL, "latitude" double precision NULL, "longitude" double precision NULL, "description" text NULL, "country_locations" uuid NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "locations_countries_locations" FOREIGN KEY ("country_locations") REFERENCES "countries" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- Create index "locations_slug_key" to table: "locations"
CREATE UNIQUE INDEX "locations_slug_key" ON "locations" ("slug");
-- Create "events" table
CREATE TABLE "events" ("id" uuid NOT NULL, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, "deleted_at" timestamptz NULL, "name" character varying NOT NULL, "slug" character varying NOT NULL, "year" bigint NOT NULL, "start_date" timestamptz NOT NULL, "end_date" timestamptz NOT NULL, "status" character varying NOT NULL DEFAULT 'draft', "description" text NULL, "settings" jsonb NULL, "logo_url" character varying NULL, "banner_url" character varying NULL, "rules_url" character varying NULL, "teams_count" bigint NOT NULL DEFAULT 0, "games_count" bigint NOT NULL DEFAULT 0, "score_edit_approval_role" character varying NOT NULL DEFAULT 'event_manager', "discipline_events" uuid NOT NULL, "location_events" uuid NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "events_disciplines_events" FOREIGN KEY ("discipline_events") REFERENCES "disciplines" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT "events_locations_events" FOREIGN KEY ("location_events") REFERENCES "locations" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- Create index "events_slug_key" to table: "events"
CREATE UNIQUE INDEX "events_slug_key" ON "events" ("slug");
-- Create "game_rounds" table
CREATE TABLE "game_rounds" ("id" uuid NOT NULL, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, "deleted_at" timestamptz NULL, "name" character varying NOT NULL, "round_type" character varying NOT NULL, "round_number" bigint NULL, "start_date" timestamptz NULL, "end_date" timestamptz NULL, "auto_advance" boolean NOT NULL DEFAULT false, "top_n_teams" bigint NULL, "event_game_rounds" uuid NOT NULL, "game_round_target_round" uuid NULL, PRIMARY KEY ("id"), CONSTRAINT "game_rounds_events_game_rounds" FOREIGN KEY ("event_game_rounds") REFERENCES "events" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT "game_rounds_game_rounds_target_round" FOREIGN KEY ("game_round_target_round") REFERENCES "game_rounds" ("id") ON UPDATE NO ACTION ON DELETE SET NULL);
-- Create index "game_rounds_game_round_target_round_key" to table: "game_rounds"
CREATE UNIQUE INDEX "game_rounds_game_round_target_round_key" ON "game_rounds" ("game_round_target_round");
-- Create "division_pools" table
CREATE TABLE "division_pools" ("id" uuid NOT NULL, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, "deleted_at" timestamptz NULL, "name" character varying NOT NULL, "division_type" character varying NOT NULL, "max_teams" bigint NULL, "ranking_criteria" jsonb NULL, "description" text NULL, "auto_advance" boolean NOT NULL DEFAULT false, "top_n_teams" bigint NULL, "division_pool_target_round" uuid NULL, "event_division_pools" uuid NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "division_pools_events_division_pools" FOREIGN KEY ("event_division_pools") REFERENCES "events" ("id") ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT "division_pools_game_rounds_target_round" FOREIGN KEY ("division_pool_target_round") REFERENCES "game_rounds" ("id") ON UPDATE NO ACTION ON DELETE SET NULL);
-- Create "categories" table
CREATE TABLE "categories" ("id" uuid NOT NULL, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, "deleted_at" timestamptz NULL, "name" character varying NOT NULL, "slug" character varying NOT NULL, "description" text NULL, PRIMARY KEY ("id"));
-- Create index "categories_slug_key" to table: "categories"
CREATE UNIQUE INDEX "categories_slug_key" ON "categories" ("slug");
-- Create "event_categories" table
CREATE TABLE "event_categories" ("event_id" uuid NOT NULL, "category_id" uuid NOT NULL, PRIMARY KEY ("event_id", "category_id"), CONSTRAINT "event_categories_category_id" FOREIGN KEY ("category_id") REFERENCES "categories" ("id") ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT "event_categories_event_id" FOREIGN KEY ("event_id") REFERENCES "events" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
-- Create "event_managed_by" table
CREATE TABLE "event_managed_by" ("event_id" uuid NOT NULL, "user_id" uuid NOT NULL, PRIMARY KEY ("event_id", "user_id"), CONSTRAINT "event_managed_by_event_id" FOREIGN KEY ("event_id") REFERENCES "events" ("id") ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT "event_managed_by_user_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
-- Create "teams" table
CREATE TABLE "teams" ("id" uuid NOT NULL, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, "deleted_at" timestamptz NULL, "name" character varying NOT NULL, "initial_seed" bigint NULL, "final_placement" bigint NULL, "logo_url" character varying NULL, "primary_color" character varying NULL, "secondary_color" character varying NULL, "contact_email" character varying NULL, "contact_phone" character varying NULL, "metadata" jsonb NULL, "division_pool_id" uuid NOT NULL, "home_location_id" uuid NULL, PRIMARY KEY ("id"), CONSTRAINT "teams_division_pools_teams" FOREIGN KEY ("division_pool_id") REFERENCES "division_pools" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT "teams_locations_teams" FOREIGN KEY ("home_location_id") REFERENCES "locations" ("id") ON UPDATE NO ACTION ON DELETE SET NULL);
-- Create "players" table
CREATE TABLE "players" ("id" uuid NOT NULL, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, "deleted_at" timestamptz NULL, "name" character varying NOT NULL, "email" character varying NULL, "gender" character varying NOT NULL, "date_of_birth" timestamptz NULL, "jersey_number" bigint NULL, "profile_image_url" character varying NULL, "is_captain" boolean NOT NULL DEFAULT false, "is_spirit_captain" boolean NOT NULL DEFAULT false, "phone" character varying NULL, "position" character varying NULL, "metadata" jsonb NULL, "team_id" uuid NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "players_teams_players" FOREIGN KEY ("team_id") REFERENCES "teams" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- Create index "players_email_key" to table: "players"
CREATE UNIQUE INDEX "players_email_key" ON "players" ("email");
-- Create "event_participations" table
CREATE TABLE "event_participations" ("id" uuid NOT NULL, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, "deleted_at" timestamptz NULL, "role" character varying NOT NULL DEFAULT 'player', "jersey_number" bigint NULL, "position" character varying NULL, "is_captain" boolean NOT NULL DEFAULT false, "is_spirit_captain" boolean NOT NULL DEFAULT false, "status" character varying NOT NULL DEFAULT 'active', "metadata" jsonb NULL, "event_participations" uuid NOT NULL, "player_participations" uuid NOT NULL, "team_participations" uuid NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "event_participations_events_participations" FOREIGN KEY ("event_participations") REFERENCES "events" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT "event_participations_players_participations" FOREIGN KEY ("player_participations") REFERENCES "players" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT "event_participations_teams_participations" FOREIGN KEY ("team_participations") REFERENCES "teams" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- Create "event_reconciliations" table
CREATE TABLE "event_reconciliations" ("id" uuid NOT NULL, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, "deleted_at" timestamptz NULL, "reconciled_at" timestamptz NOT NULL, "reconciled_by" character varying NOT NULL, "status" character varying NOT NULL DEFAULT 'pending', "comments" text NULL, "event_reconciliations" uuid NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "event_reconciliations_events_reconciliations" FOREIGN KEY ("event_reconciliations") REFERENCES "events" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
-- Create "fields" table
CREATE TABLE "fields" ("id" uuid NOT NULL, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, "deleted_at" timestamptz NULL, "name" character varying NOT NULL, "capacity" bigint NULL, "surface_type" character varying NULL, "metadata" jsonb NULL, "location_fields" uuid NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "fields_locations_fields" FOREIGN KEY ("location_fields") REFERENCES "locations" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- Create "games" table
CREATE TABLE "games" ("id" uuid NOT NULL, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, "deleted_at" timestamptz NULL, "name" character varying NOT NULL, "scheduled_time" timestamptz NOT NULL, "actual_start_time" timestamptz NULL, "actual_end_time" timestamptz NULL, "allocated_time_minutes" bigint NOT NULL, "stoppage_time_seconds" bigint NOT NULL DEFAULT 0, "status" character varying NOT NULL DEFAULT 'scheduled', "home_team_score" bigint NOT NULL DEFAULT 0, "away_team_score" bigint NOT NULL DEFAULT 0, "first_pull_by" character varying NULL, "version" bigint NOT NULL DEFAULT 1, "metadata" jsonb NULL, "division_pool_games" uuid NOT NULL, "field_games" uuid NOT NULL, "game_round_games" uuid NULL, "team_home_games" uuid NOT NULL, "team_away_games" uuid NOT NULL, "user_officiated_games" uuid NULL, PRIMARY KEY ("id"), CONSTRAINT "games_division_pools_games" FOREIGN KEY ("division_pool_games") REFERENCES "division_pools" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT "games_fields_games" FOREIGN KEY ("field_games") REFERENCES "fields" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT "games_game_rounds_games" FOREIGN KEY ("game_round_games") REFERENCES "game_rounds" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, CONSTRAINT "games_teams_away_games" FOREIGN KEY ("team_away_games") REFERENCES "teams" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT "games_teams_home_games" FOREIGN KEY ("team_home_games") REFERENCES "teams" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT "games_users_officiated_games" FOREIGN KEY ("user_officiated_games") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL);
-- Create index "games_name_key" to table: "games"
CREATE UNIQUE INDEX "games_name_key" ON "games" ("name");
-- Create "game_events" table
CREATE TABLE "game_events" ("id" uuid NOT NULL, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, "deleted_at" timestamptz NULL, "event_type" character varying NOT NULL, "minute" bigint NOT NULL, "second" bigint NOT NULL, "description" text NULL, "metadata" jsonb NULL, "game_game_events" uuid NOT NULL, "player_game_events" uuid NULL, PRIMARY KEY ("id"), CONSTRAINT "game_events_games_game_events" FOREIGN KEY ("game_game_events") REFERENCES "games" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT "game_events_players_game_events" FOREIGN KEY ("player_game_events") REFERENCES "players" ("id") ON UPDATE NO ACTION ON DELETE SET NULL);
-- Create "spirit_scores" table
CREATE TABLE "spirit_scores" ("id" uuid NOT NULL, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, "deleted_at" timestamptz NULL, "rules_knowledge" bigint NOT NULL, "fouls_body_contact" bigint NOT NULL, "fair_mindedness" bigint NOT NULL, "attitude" bigint NOT NULL, "communication" bigint NOT NULL, "comments" text NULL, "game_spirit_scores" uuid NOT NULL, "team_spirit_scores_given" uuid NOT NULL, "team_spirit_scores_received" uuid NOT NULL, "user_submitted_spirit_scores" uuid NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "spirit_scores_games_spirit_scores" FOREIGN KEY ("game_spirit_scores") REFERENCES "games" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT "spirit_scores_teams_spirit_scores_given" FOREIGN KEY ("team_spirit_scores_given") REFERENCES "teams" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT "spirit_scores_teams_spirit_scores_received" FOREIGN KEY ("team_spirit_scores_received") REFERENCES "teams" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT "spirit_scores_users_submitted_spirit_scores" FOREIGN KEY ("user_submitted_spirit_scores") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- Create "mvp_nominations" table
CREATE TABLE "mvp_nominations" ("id" uuid NOT NULL, "category" character varying NOT NULL, "created_at" timestamptz NOT NULL, "player_mvp_nominations" uuid NOT NULL, "spirit_score_mvp_nominations" uuid NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "mvp_nominations_players_mvp_nominations" FOREIGN KEY ("player_mvp_nominations") REFERENCES "players" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT "mvp_nominations_spirit_scores_mvp_nominations" FOREIGN KEY ("spirit_score_mvp_nominations") REFERENCES "spirit_scores" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- Create "scoped_roles" table
CREATE TABLE "scoped_roles" ("id" uuid NOT NULL, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, "deleted_at" timestamptz NULL, "role" character varying NOT NULL, "scope_type" character varying NOT NULL, "scope_id" uuid NOT NULL, "permissions" jsonb NULL, "user_id" uuid NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "scoped_roles_users_scoped_roles" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- Create "score_edit_requests" table
CREATE TABLE "score_edit_requests" ("id" uuid NOT NULL, "previous_home_score" bigint NOT NULL, "previous_away_score" bigint NOT NULL, "new_home_score" bigint NOT NULL, "new_away_score" bigint NOT NULL, "reason" character varying NOT NULL, "status" character varying NOT NULL DEFAULT 'pending', "rejection_reason" character varying NULL, "reviewed_at" timestamptz NULL, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, "player_scores" jsonb NULL, "game_id" uuid NOT NULL, "reviewed_by_id" uuid NULL, "requested_by_id" uuid NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "score_edit_requests_games_score_edit_requests" FOREIGN KEY ("game_id") REFERENCES "games" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT "score_edit_requests_users_reviewed_by" FOREIGN KEY ("reviewed_by_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, CONSTRAINT "score_edit_requests_users_score_edit_requests" FOREIGN KEY ("requested_by_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- Create "scorings" table
CREATE TABLE "scorings" ("id" uuid NOT NULL, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, "deleted_at" timestamptz NULL, "goals" bigint NOT NULL DEFAULT 0, "assists" bigint NOT NULL DEFAULT 0, "blocks" bigint NOT NULL DEFAULT 0, "turns" bigint NOT NULL DEFAULT 0, "version" bigint NOT NULL DEFAULT 1, "game_scores" uuid NOT NULL, "player_scores" uuid NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "scorings_games_scores" FOREIGN KEY ("game_scores") REFERENCES "games" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT "scorings_players_scores" FOREIGN KEY ("player_scores") REFERENCES "players" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- Create "spirit_nominations" table
CREATE TABLE "spirit_nominations" ("id" uuid NOT NULL, "category" character varying NOT NULL, "created_at" timestamptz NOT NULL, "player_spirit_nominations" uuid NOT NULL, "spirit_score_spirit_nominations" uuid NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "spirit_nominations_players_spirit_nominations" FOREIGN KEY ("player_spirit_nominations") REFERENCES "players" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT "spirit_nominations_spirit_scores_spirit_nominations" FOREIGN KEY ("spirit_score_spirit_nominations") REFERENCES "spirit_scores" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- Create "team_managed_by" table
CREATE TABLE "team_managed_by" ("team_id" uuid NOT NULL, "user_id" uuid NOT NULL, PRIMARY KEY ("team_id", "user_id"), CONSTRAINT "team_managed_by_team_id" FOREIGN KEY ("team_id") REFERENCES "teams" ("id") ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT "team_managed_by_user_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
