// Code generated by ent, DO NOT EDIT.

package user

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldEmail holds the string denoting the email field in the database.
	FieldEmail = "email"
	// FieldPasswordHash holds the string denoting the password_hash field in the database.
	FieldPasswordHash = "password_hash"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldAvatarURL holds the string denoting the avatar_url field in the database.
	FieldAvatarURL = "avatar_url"
	// FieldRole holds the string denoting the role field in the database.
	FieldRole = "role"
	// FieldIsActive holds the string denoting the is_active field in the database.
	FieldIsActive = "is_active"
	// FieldLastLoginAt holds the string denoting the last_login_at field in the database.
	FieldLastLoginAt = "last_login_at"
	// EdgeManagedContinent holds the string denoting the managed_continent edge name in mutations.
	EdgeManagedContinent = "managed_continent"
	// EdgeManagedCountry holds the string denoting the managed_country edge name in mutations.
	EdgeManagedCountry = "managed_country"
	// EdgeManagedDiscipline holds the string denoting the managed_discipline edge name in mutations.
	EdgeManagedDiscipline = "managed_discipline"
	// EdgeManagedEvent holds the string denoting the managed_event edge name in mutations.
	EdgeManagedEvent = "managed_event"
	// EdgeManagedTeam holds the string denoting the managed_team edge name in mutations.
	EdgeManagedTeam = "managed_team"
	// EdgeOfficiatedGames holds the string denoting the officiated_games edge name in mutations.
	EdgeOfficiatedGames = "officiated_games"
	// EdgeScopedRoles holds the string denoting the scoped_roles edge name in mutations.
	EdgeScopedRoles = "scoped_roles"
	// EdgeSubmittedSpiritScores holds the string denoting the submitted_spirit_scores edge name in mutations.
	EdgeSubmittedSpiritScores = "submitted_spirit_scores"
	// EdgeScoreEditRequests holds the string denoting the score_edit_requests edge name in mutations.
	EdgeScoreEditRequests = "score_edit_requests"
	// Table holds the table name of the user in the database.
	Table = "users"
	// ManagedContinentTable is the table that holds the managed_continent relation/edge. The primary key declared below.
	ManagedContinentTable = "continent_managed_by"
	// ManagedContinentInverseTable is the table name for the Continent entity.
	// It exists in this package in order to avoid circular dependency with the "continent" package.
	ManagedContinentInverseTable = "continents"
	// ManagedCountryTable is the table that holds the managed_country relation/edge. The primary key declared below.
	ManagedCountryTable = "country_managed_by"
	// ManagedCountryInverseTable is the table name for the Country entity.
	// It exists in this package in order to avoid circular dependency with the "country" package.
	ManagedCountryInverseTable = "countries"
	// ManagedDisciplineTable is the table that holds the managed_discipline relation/edge. The primary key declared below.
	ManagedDisciplineTable = "discipline_managed_by"
	// ManagedDisciplineInverseTable is the table name for the Discipline entity.
	// It exists in this package in order to avoid circular dependency with the "discipline" package.
	ManagedDisciplineInverseTable = "disciplines"
	// ManagedEventTable is the table that holds the managed_event relation/edge. The primary key declared below.
	ManagedEventTable = "event_managed_by"
	// ManagedEventInverseTable is the table name for the Event entity.
	// It exists in this package in order to avoid circular dependency with the "event" package.
	ManagedEventInverseTable = "events"
	// ManagedTeamTable is the table that holds the managed_team relation/edge. The primary key declared below.
	ManagedTeamTable = "team_managed_by"
	// ManagedTeamInverseTable is the table name for the Team entity.
	// It exists in this package in order to avoid circular dependency with the "team" package.
	ManagedTeamInverseTable = "teams"
	// OfficiatedGamesTable is the table that holds the officiated_games relation/edge.
	OfficiatedGamesTable = "games"
	// OfficiatedGamesInverseTable is the table name for the Game entity.
	// It exists in this package in order to avoid circular dependency with the "game" package.
	OfficiatedGamesInverseTable = "games"
	// OfficiatedGamesColumn is the table column denoting the officiated_games relation/edge.
	OfficiatedGamesColumn = "user_officiated_games"
	// ScopedRolesTable is the table that holds the scoped_roles relation/edge.
	ScopedRolesTable = "scoped_roles"
	// ScopedRolesInverseTable is the table name for the ScopedRole entity.
	// It exists in this package in order to avoid circular dependency with the "scopedrole" package.
	ScopedRolesInverseTable = "scoped_roles"
	// ScopedRolesColumn is the table column denoting the scoped_roles relation/edge.
	ScopedRolesColumn = "user_id"
	// SubmittedSpiritScoresTable is the table that holds the submitted_spirit_scores relation/edge.
	SubmittedSpiritScoresTable = "spirit_scores"
	// SubmittedSpiritScoresInverseTable is the table name for the SpiritScore entity.
	// It exists in this package in order to avoid circular dependency with the "spiritscore" package.
	SubmittedSpiritScoresInverseTable = "spirit_scores"
	// SubmittedSpiritScoresColumn is the table column denoting the submitted_spirit_scores relation/edge.
	SubmittedSpiritScoresColumn = "user_submitted_spirit_scores"
	// ScoreEditRequestsTable is the table that holds the score_edit_requests relation/edge.
	ScoreEditRequestsTable = "score_edit_requests"
	// ScoreEditRequestsInverseTable is the table name for the ScoreEditRequest entity.
	// It exists in this package in order to avoid circular dependency with the "scoreeditrequest" package.
	ScoreEditRequestsInverseTable = "score_edit_requests"
	// ScoreEditRequestsColumn is the table column denoting the score_edit_requests relation/edge.
	ScoreEditRequestsColumn = "requested_by_id"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldEmail,
	FieldPasswordHash,
	FieldName,
	FieldAvatarURL,
	FieldRole,
	FieldIsActive,
	FieldLastLoginAt,
}

var (
	// ManagedContinentPrimaryKey and ManagedContinentColumn2 are the table columns denoting the
	// primary key for the managed_continent relation (M2M).
	ManagedContinentPrimaryKey = []string{"continent_id", "user_id"}
	// ManagedCountryPrimaryKey and ManagedCountryColumn2 are the table columns denoting the
	// primary key for the managed_country relation (M2M).
	ManagedCountryPrimaryKey = []string{"country_id", "user_id"}
	// ManagedDisciplinePrimaryKey and ManagedDisciplineColumn2 are the table columns denoting the
	// primary key for the managed_discipline relation (M2M).
	ManagedDisciplinePrimaryKey = []string{"discipline_id", "user_id"}
	// ManagedEventPrimaryKey and ManagedEventColumn2 are the table columns denoting the
	// primary key for the managed_event relation (M2M).
	ManagedEventPrimaryKey = []string{"event_id", "user_id"}
	// ManagedTeamPrimaryKey and ManagedTeamColumn2 are the table columns denoting the
	// primary key for the managed_team relation (M2M).
	ManagedTeamPrimaryKey = []string{"team_id", "user_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// EmailValidator is a validator for the "email" field. It is called by the builders before save.
	EmailValidator func(string) error
	// PasswordHashValidator is a validator for the "password_hash" field. It is called by the builders before save.
	PasswordHashValidator func(string) error
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// RoleValidator is a validator for the "role" field. It is called by the builders before save.
	RoleValidator func(string) error
	// DefaultIsActive holds the default value on creation for the "is_active" field.
	DefaultIsActive bool
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the User queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByEmail orders the results by the email field.
func ByEmail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEmail, opts...).ToFunc()
}

// ByPasswordHash orders the results by the password_hash field.
func ByPasswordHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPasswordHash, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByAvatarURL orders the results by the avatar_url field.
func ByAvatarURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAvatarURL, opts...).ToFunc()
}

// ByRole orders the results by the role field.
func ByRole(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRole, opts...).ToFunc()
}

// ByIsActive orders the results by the is_active field.
func ByIsActive(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsActive, opts...).ToFunc()
}

// ByLastLoginAt orders the results by the last_login_at field.
func ByLastLoginAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastLoginAt, opts...).ToFunc()
}

// ByManagedContinentCount orders the results by managed_continent count.
func ByManagedContinentCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newManagedContinentStep(), opts...)
	}
}

// ByManagedContinent orders the results by managed_continent terms.
func ByManagedContinent(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newManagedContinentStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByManagedCountryCount orders the results by managed_country count.
func ByManagedCountryCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newManagedCountryStep(), opts...)
	}
}

// ByManagedCountry orders the results by managed_country terms.
func ByManagedCountry(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newManagedCountryStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByManagedDisciplineCount orders the results by managed_discipline count.
func ByManagedDisciplineCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newManagedDisciplineStep(), opts...)
	}
}

// ByManagedDiscipline orders the results by managed_discipline terms.
func ByManagedDiscipline(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newManagedDisciplineStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByManagedEventCount orders the results by managed_event count.
func ByManagedEventCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newManagedEventStep(), opts...)
	}
}

// ByManagedEvent orders the results by managed_event terms.
func ByManagedEvent(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newManagedEventStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByManagedTeamCount orders the results by managed_team count.
func ByManagedTeamCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newManagedTeamStep(), opts...)
	}
}

// ByManagedTeam orders the results by managed_team terms.
func ByManagedTeam(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newManagedTeamStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByOfficiatedGamesCount orders the results by officiated_games count.
func ByOfficiatedGamesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newOfficiatedGamesStep(), opts...)
	}
}

// ByOfficiatedGames orders the results by officiated_games terms.
func ByOfficiatedGames(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newOfficiatedGamesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByScopedRolesCount orders the results by scoped_roles count.
func ByScopedRolesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newScopedRolesStep(), opts...)
	}
}

// ByScopedRoles orders the results by scoped_roles terms.
func ByScopedRoles(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newScopedRolesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// BySubmittedSpiritScoresCount orders the results by submitted_spirit_scores count.
func BySubmittedSpiritScoresCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newSubmittedSpiritScoresStep(), opts...)
	}
}

// BySubmittedSpiritScores orders the results by submitted_spirit_scores terms.
func BySubmittedSpiritScores(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSubmittedSpiritScoresStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByScoreEditRequestsCount orders the results by score_edit_requests count.
func ByScoreEditRequestsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newScoreEditRequestsStep(), opts...)
	}
}

// ByScoreEditRequests orders the results by score_edit_requests terms.
func ByScoreEditRequests(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newScoreEditRequestsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newManagedContinentStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ManagedContinentInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, true, ManagedContinentTable, ManagedContinentPrimaryKey...),
	)
}
func newManagedCountryStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ManagedCountryInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, true, ManagedCountryTable, ManagedCountryPrimaryKey...),
	)
}
func newManagedDisciplineStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ManagedDisciplineInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, true, ManagedDisciplineTable, ManagedDisciplinePrimaryKey...),
	)
}
func newManagedEventStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ManagedEventInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, true, ManagedEventTable, ManagedEventPrimaryKey...),
	)
}
func newManagedTeamStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ManagedTeamInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, true, ManagedTeamTable, ManagedTeamPrimaryKey...),
	)
}
func newOfficiatedGamesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(OfficiatedGamesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, OfficiatedGamesTable, OfficiatedGamesColumn),
	)
}
func newScopedRolesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ScopedRolesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ScopedRolesTable, ScopedRolesColumn),
	)
}
func newSubmittedSpiritScoresStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SubmittedSpiritScoresInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, SubmittedSpiritScoresTable, SubmittedSpiritScoresColumn),
	)
}
func newScoreEditRequestsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ScoreEditRequestsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ScoreEditRequestsTable, ScoreEditRequestsColumn),
	)
}
